### ISSUE TITLE
keepCopiesInStore option not recognized

### ISSUE THREAD

**Issue by jscottsf** [feathersjs-ecosystem/feathers-vuex#232]
### Steps to reproduce

1. Assign `keepCopiesInStore` to `true`.
2. Call `clone()` on a model and then inspect `$FeathersVuex.MyModel.copiesById`.

You'll see the id listed here which is the wrong behavior.

Digging further, if you debug log `state` inside the service module method `createCopy`, you'll see that `keepCopiesInStore` is undefined.

The reason is that `keepCopiesInStore` is missing from the `state` var in `state.js`. In short, the option is not copied to the state.

**Comment by marshallswain** [comment]
@jscottsf, thanks for debugging!  Is this with the current `latest` or with the pre-release?

**Comment by marshallswain** [comment]
Also, you might already be aware that keeping copies in the store means you will probably either violate Vuex strict mode (by modifying copies), or you're going to plan on writing a bunch of boilerplate code to play nice with Vuex mode.  (There's always option three: ignore Vuex strict mode.)  Just FYI.

**Comment by marshallswain** [comment]
I'm planning on deprecating the `keepCopesInStore` option.  The current plan is to remove it in version 4.0.  Version 3.0 will be released within a couple of days.

**Comment by marshallswain** [comment]
I will of course listen to any reasons why we should leave it in.  I just don't see a reason for it.  I added it to be flexible, but I just don't see any reason to use it, now.

**Comment by marshallswain** [comment]
Heh.  It turns out there was one reason to use it, because `Models.copiesById` was accidentally shared by all Models, you could run into conflicts.  I've fixed the bug in `feathers-vuex@3.0.1`, which was published this morning.
