### ISSUE TITLE
Can't find a working example application

### ISSUE THREAD

**Issue by findingorder** [feathersjs-ecosystem/feathers-vuex#252]
For a few days now I've been searching in vain on the web for a *working* example application that I can use as a starting place for learning feathers-vuex.  The obvious choice would be https://github.com/feathers-plus/feathers-chat-vuex, but it is quite out of date and throws all sorts of errors when you try to build and run it.

Does anyone know of a good, *current*, *working* example application that I can download and run on my local computer?

BTW, the demo application referenced in README, https://codesandbox.io/s/xk52mqm7o, is nice, but I can't figure out how to run it outside codesandbox.io. If someone could explain how to do this, that might be the answer to my problem.

Thanks in advance!

**Comment by marshallswain** [comment]
I agree.  An up-to-date demo application would be nice to have.  Until one turns up, you'll probably have better luck copying and pasting from the documentation.  I recommend starting out with the PR for the pre-release: https://github.com/feathers-plus/feathers-vuex/pull/216.  There's a decent section on getting started that you should be able to copy and paste into a new project.

Someday I will create time to create a demo application.  In the meantime, we're happy to answer questions on Slack in the #vue channel.

**Comment by lturel** [comment]
Hi Marshall,   explanations in  #216 very detailed, thank you for that.  I tried a simple starting project in Feathers V4 + Authentication and Feathers-Vuex 2.0  (pre-75), and could not get to create a new user in 'users' table  with default fields (email and password).  
I imagine, you are very busy with issues of new version, but a simple Todo app with Feathers V4 + Authenticaton using Feathers-Vuex 2.0  would be very helpful.
Thanks a lot.

**Comment by eikaramba** [comment]
it is te same currently for me. i was able to setup a feathers backend together with a Feathers V4 + feathers-vuex 2.0 frontend based on the information available in #216 - but now i'm struggling to make the simplest CRUD operation work (i have to admit that i am a reactive noob and used a simple REST client before without any store or anything, but i want to learn!)

If you could make a really simple example i think that would help a lot of us a lot of time :)

**Comment by eikaramba** [comment]
i made it work!
2 hints that were helping:
1) Create the vue.config.js file in the root directory with
```
module.exports = {
  transpileDependencies: ["feathers-vuex"]
};
```
2) Try to disable authentication for the sample feathers users find hook ;)

Now creating a user and retrieving them works like this

```
<template>
  <div class="about">
    <h1>users</h1>
    <form @submit.prevent="createUser">
        <input v-model="user.email">
        <input v-model="user.password">
        <label>Create New User: {{user.email}}</label>
        <button type="submit" :disabled="!user.email">Create</button>
    </form>
    <div v-if="loading">Erstelle...</div>

      <div v-for="user in users().data" :key="user._id">
          {{ user.email }}
      </div>
  </div>
</template>


<script>
import { mapActions, mapState, mapGetters } from 'vuex'
export default {
  name: 'about',
  data: () => ({
    user: {
      email:'',
      password:''
    }
  }),
  computed: { // only getters have live queries
    ...mapGetters('users', {users: 'find'}),
    ...mapState('users', {loading: 'isCreatePending'})
  },
  methods: {
    createUser(){
      const { User } = this.$FeathersVuex.api;
      const user = new User(this.user);
      user.save().then(user => {
        console.log(user);
        // this.$router.push('/');
      })
    },
    ...mapActions('users', ['create', 'remove', 'find'])
  },
  created: async function () {
    await this.find().then(function(data){
      console.log("show me the users",data);
    })
  }
}
</script>
```

**Comment by lturel** [comment]
Hey **eikaramba**,  thanks for the information you provided.
For not missing the links or some critical detail, could you give the link for complete source on GitHub, if exists. Or zip file which we can download.

Thanks in advance,

**Comment by eikaramba** [comment]
That is unfortunately not so easy, but i can guarantee you that i just used feathers-cli to setup a folder /backend with the standard configuration. i didn't do anything there apart from removing the authentication hook for the find service

on the frontend i uses the vue-cli to setup a js project with vuex and router. Then follow the guide on https://github.com/feathers-plus/feathers-vuex/pull/216 and you should be ready to go.

**Comment by lturel** [comment]
@eikaramba, super.
Thanks for guiding,  
All the best.

**Comment by J3m5** [comment]
I'm working on an example app, I'll submit a PR soon.

**Comment by findingorder** [comment]
Thanks for your responses, everyone. I see I'm not the only noob struggling with this.

It's beyond the scope of this thread, but what I **really** want is a ready-to-roll scaffold that has Quasar for the client, and vuex + feathers on the back end, with authentication built and working on both client and server.  This would free me up to start writing Vue components and creating data schemas without spending so much time on "plumbing".  Might have to assemble this myself.

**Comment by findingorder** [comment]
Leaving the thread open in case others want to comment, but the feathers-plus/feathers-vuex maintainers are free to close whenever they deem appropriate.

**Comment by pcrombach** [comment]
As far as I understand is Vuex a frontend thingy, not backend. I’m rebuilding an old Angular / Ionic v1 / and feathers-vuex v1 frontend into a Vue with Ionic v4 with feathers V2 frontend. I was thinking about to start a blog about the steps I made. If there are more people waiting for this, let me hear about you.

**Comment by findingorder** [comment]
Yes, of course.  I should have said Feathers on the backend, and Vuex on the front end syncing with Feathers on the back end.

**Comment by wdmtech** [comment]
I made this some time ago, and it should still work

https://github.com/wdmtech/feathers-vuex-todomvc

**Comment by dkebler** [comment]
@findingorder 

https://git.kebler.net/Light2/frontend/src/branch/v1  (v1 branch)
I have 2.0 pre FV working in this app/repo above.  Anyone welcome to look/clone.
It's part of a larger quasar app so might be a bit confusing unless you are already familiar with quasar.

I used a boot file (a quasar thing for loading vue plugins)  `/src/boot/database.js`  to load FV later after the store was created in `src/store.index.js` so I could grab the service names from the backend and then dynamically create the FV plugins instead of hard coding the services using this trick https://stackoverflow.com/questions/50959594/dynamically-register-a-vuex-plugin

It does that via function in /src/store/vuex-feathers which uses a createModelClass function to create a model class on the fly.  See #271

```javascript
import fVuex from 'feathers-vuex'

const addFeathers = async (store, db, opts = {}) => {
  store.state.services = db.collections

  const { makeServicePlugin, BaseModel } = fVuex(db.api, { serverAlias: opts.alias || 'api' })

  function createModelClass (name, Base) {
    const nameIt = (name, cls) => ({ [name]: class extends cls {} })[name]
    class Model extends Base {
      constructor (data, options) {
        super(data, options)
        this.modelName = name
      }
    static modelName = name
    }
    return nameIt(name, Model)
  }

 // registering plugins dyanmically here per a trick
// https://stackoverflow.com/questions/50959594/dynamically-register-a-vuex-plugin
  db.collections.forEach(name =>
    makeServicePlugin({ Model: createModelClass(name, BaseModel), service: db.api.service(name) })(store)
  )
}
export default addFeathers
```

**Comment by lturel** [comment]
A starting project utilizing  Feathers 4 + Authentication + Vue + Feathers-Vuex 2.0 + Vuetify

https://github.com/lturel/Feathers4-Vue-FVuex2.git

**Comment by knowsarzehmeh** [comment]
Any example project for utilizing Feathers 4 + Authentication + Feathers vuex with Nuxtjs?

**Comment by janzheng** [comment]
@lturel if you don't mind, I created a quick demo that reconfigures a lot of your code to work with the feathers-chat server example. That `feathers-vuex` documentation is quite the pain for someone new to feathers. Anyway, here's the repo if it helps anyone: https://github.com/janzheng/feathers-vuex-chat

**Comment by marshallswain** [comment]
@janzheng that's a really good point.  The docs pretty much assume knowledge of Feathers.  There's not a beginners section.  It's ironically funny because just before reading your message, I was looking in amazement at how much documentation I've written for `feathers-vuex`.  Yet, still, there's so much more that could be done.  

I'm really happy to see that a lot of community members have started contributing.  That has been really supportive.  Thank you.

I'm wrapping up tests and documentation for Feathers-Vuex 3.0.  Once complete, I'm going to create a new demo application using the Vue Composition API.

**Comment by janzheng** [comment]
@marshallswain Thanks for all your hard work!!! The docs are super in-depth! I just got through the feathers-chat example, but had trouble continuing recreating the example in vue/vuex, from a "how do I hook up a client to the server I'd just built in feathers." I think I still kind of lack the basic context of how "feathers works" — I realized that a lot of the material on the tutorial is super advanced stuff and not required to just `find` or `create` data — but after playing with it I keep thinking "wow this is so easy...!" so that's really good ;)

that's awesome, and really looking forward to seeing the new demo with Composition!

**Comment by lturel** [comment]
@janzheng thanks for adding feathers-chat example.
It will be very useful for novice programmers on feathers like me :)

**Comment by marshallswain** [comment]
We have a new page for keeping track of example applications: https://vuex.feathersjs.com/example-applications.html.  It includes the recent refactor of the example [Feathers Chat app built on the newest feathers-vuex@3.x](https://github.com/feathersjs-ecosystem/feathers-chat-vuex).

Please feel free to add any you find to the list in the docs.

**Comment by akvaliya** [comment]
Any example with nuxt?

**Comment by marshallswain** [comment]
@akvaliya Yup!  in the docs: https://vuex.feathersjs.com/common-patterns.html#full-nuxt-example

**Comment by pliersch** [comment]
Hello, i cant find the source code of the full nuxt example. I'm blind?

**Comment by marshallswain** [comment]
It’s directly in the docs. Not in a repo
