### ISSUE TITLE
Financial Support

### ISSUE THREAD

**Issue by RubyRubenstahl** [feathersjs-ecosystem/feathers-vuex#253]
I'm curious to find out if you are currently accepting financial support on any platform or if you're drawing from the feathers Open Collective fund?

A core tenant of the company  I work for is to treat everyone involved in our business equitably including clients, employees, and our supply chain. 

As we're making extensive use of open source libraries & frameworks, we've made the decision to charge an "open-source" fee on our projects in order to ensure that we can help support the people who make our work possible. 

We've already started donating to the core feathers team, but I want to make sure that feathers-vuex isn't being left out, as it saves me countless hours of work and there clearly has been a lot of work going into it. 

If feathers-vuex were to accept donations, it would be next on my list when funds are available.

**Comment by adrianofoschi** [comment]
+1 I would make a donation

**Comment by marshallswain** [comment]
Thanks @RubyRubenstahl and @adrianofoschi!  This is all very kind.  I applied for GitHub Sponsors a few weeks ago.  Still awaiting the invite.  I'll update this issue when I have an update.

**Comment by marshallswain** [comment]
GitHub sponsorship is ready, now.  I'm going to go ahead and close this.  Thank you!
