### ISSUE TITLE
Vue DevTools open with Feathers Vuex 2 much slower than Feathers Vuex 1

### ISSUE THREAD

**Issue by martinfruehmorgen** [feathersjs-ecosystem/feathers-vuex#275]
I am trying to use latest FeathersJS (4.3.3) with prerelease Feathers-Vuex 2.0.0-pre.77 (solution to issue #247).

When comparing feathers-vuex 1.7.0 and feathers-vuex 2.0.0-pre.77 with exactly the same code
```
<template>
  <div class="about">
    <h1>users</h1>
      <div v-for="user in kontakte" :key="user.id">
          {{ user.value }}
      </div>
  </div>
</template>

<script>
import { makeFindMixin } from 'feathers-vuex'
export default {
  name: 'about',
  mixins: [
    makeFindMixin({
      service: 'kontakte',
      watch: true
      // local: true
    })
  ],
  computed: { // only getters have live queries
    kontakteParams () {
      return {
        paginate: false,
        query: {
          $limit: 100,
          $sort: {
            value: 1
          }
        }
        // temps: false
      }
    }
  },
  methods: {
  }
}
</script>
```

the new version feathers-vuex 2.0.0-pre.77 is much slower and even crashes the browser (with higher limit). If I check the vue console in Chrome I see the following difference in the Vuex mutations:
feathers-vuex 1.7.0:
kontakte/setFindPending
kontakte/addItems
kontakte/updateItems
kontakte/unsetFindPending

feathers-vuex 2.0.0-pre.77:
kontakte/setPending
**kontakte/addItem
kontakte/addItem
kontakte/addItem** ------ THIS 1000 times
kontakte/addItems
kontakte/updateItems
kontakte/unsetPending

The difference is that with feathers-vuex 2.0.0-pre.77 the single addItem mutation is called for each entry and probably this slows down everything... Is there a reason for this and a way to prevent this?

Thanks!
Martin

**Comment by J3m5** [comment]
Can you add
 ```js
pagniate:false
``` 

to the params object, just above the query object and see how it goes?

**Comment by martinfruehmorgen** [comment]
> ```js
> pagniate:false
> ```

Hi J3m5, thanks! I forget that in my code, but it does not help... Edited the code.

Thanks again!
Martin

**Comment by martinfruehmorgen** [comment]
> Can you add
> 
> ```js
> pagniate:false
> ```
> 
> to the params object, just above the query object and see how it goes?

Hi J3m5, thanks! I forgot that in my code while pasting (edited it now). Unfortunetely this does not help...

Thanks again!
Martin

**Comment by J3m5** [comment]
Try to remove the watch property too. It only accept a string or an array anyway.
And did you customize you model?

**Comment by martinfruehmorgen** [comment]
Hello,

I removed watch: true, which did not help.
Here is my model...
Thanks!
```
import feathersClient, {
  makeServicePlugin,
  BaseModel
} from '../feathers-client'
// Extend the base class
class Kontakte extends BaseModel {
  // eslint-disable-next-line no-useless-constructor
  constructor (data, options) {
    super(data, options)
  }
  static modelName = 'Kontakte'
  static instanceDefaults (data, { models, store }) {
    return {
    }
  }
}
const servicePath = 'kontakte'
const servicePlugin = makeServicePlugin({
  Model: Kontakte,
  service: feathersClient.service(servicePath),
  servicePath
})

export default servicePlugin

```

**Comment by ChaBen** [comment]
I have the same problem

**Comment by marshallswain** [comment]
I can confirm that this is an issue.  My theory is that it has something to do with the way the Vue devtools handle the related data between models.  There's no performance problem until you open the Vue developer tools, which is when the UI will freeze until the devtools have finished processing.  It's really annoying. 

This same problem can even occur when you have smaller datasets with many relationships.

**Comment by marshallswain** [comment]
For a development workaround, I just add a `window.vm = this` into the created hook of a component in order to inspect data.  It's much more efficient than waiting for the dev tools to finish processing.  If somebody is feeling ambitious, checking into why the dev tools take so long would be a great solution to this issue.

**Comment by marshallswain** [comment]
I will add here that if you keep your queries to a reasonable amount of data (what can be visualized on screen) the issue tends to be minimized.

**Comment by martinfruehmorgen** [comment]
> I can confirm that this is an issue. My theory is that it has something to do with the way the Vue devtools handle the related data between models. There's no performance problem until you open the Vue developer tools, which is when the UI will freeze until the devtools have finished processing. It's really annoying.
> 
> This same problem can even occur when you have smaller datasets with many relationships.

Hello,
and thanks for the replies! The problem appears not only with open dev tools, but unfortunately also when closed... Having bigger amount of data, this is really killing the browser.

Thanks again!
Martin

**Comment by marshallswain** [comment]
@martinfruehmorgen How much is a bigger amount of data?  In my testing, I'm loading 2000, decent-sized records and the browser pauses for about 1 second while it processes data on a 2005 MacBook Pro.  If you would like a specific solution of value, please provide some real data that I can use to assess the situation.  Without more specifics, no matter how long this issue remains open, it's as good as closed.
