### ISSUE TITLE
Properties added via patch are not reactive in @pre

### ISSUE THREAD

**Issue by Nico264** [feathersjs-ecosystem/feathers-vuex#276]
### Steps to reproduce

```javascript
const user = await store.dispatch('users/create', { name: 'Example' })
user.name // has getter/setter, is reactive
await store.dispatch('users/patch', [user._id, { laterality: 'left' }])
user.laterality // is plain, not reactive
```

### Expected behaviour

`user.laterality` should be reactive

### Actual behaviour

`user.laterality` is not reactive

### Cause

I think I have pinpointed the problem here: https://github.com/feathers-plus/feathers-vuex/blob/a3b414e65974ef4a9dfb45e23acccfa7085fd030/src/utils.ts#L436

There, if `dest[key]` doesn't already exist or isn't reactive, then it becomes (or stays) a plain property.
In that case, I believe we should use `Vue.set(dest, key, source[key])`.

**Comment by marshallswain** [comment]
This is one of the reasons to have well-defined `instanceDefaults`.

I would also accept a PR that performs a check and uses Vue.set, as you described, but it should include some docs about performance.

**Comment by marshallswain** [comment]
Your suggested solution is actually great as a pre-requisite to https://github.com/feathers-plus/feathers-vuex/issues/271

**Comment by dkebler** [comment]
I try to deal with this in the backend where I have a service schema.  On any create I make sure any property not set in create call will get a default value.  Then on return all props will be reactive.   There are ways in the front end but you will probably have to use Vue.set to get it reactive until the next dispatch.

**Comment by marshallswain** [comment]
I've added documentation addressing this issue in the 3.0 docs.  To be released within the next couple of days.
