### ISSUE TITLE
Authentication with NUXT

### ISSUE THREAD

**Issue by klaus1978** [feathersjs-ecosystem/feathers-vuex#337]
Hi *,
it seems the new documentation still refers to V1 regarding NUXT and authentication?

Anyway, when I try to follow the described steps I get an error when I add the auth plugin including additional options:

```js
//store/index.js
const createStore = () => {
  return new Vuex.Store({
    ...
    plugins: [
      auth({
        state: {
          publicPages: [
            'login',
            'signup'
          ]
        }
      })
    ]
```

--> ERROR:  typeError: store.registerModule is not a function

As long as I just add
> plugins: [auth] 

the error does not appear...

Best regards
klaus

**Comment by klaus1978** [comment]
Hi,
I found a solution:
Just adding the additional options to my auth.js did the trick:

> import { makeAuthPlugin } from "../feathers-client";
> 
> export default makeAuthPlugin({
>   userService: "users",
>   state: {
>     publicPages: [
>       "index", //home
>       "lang",
>       // "lang-pages",
>       "lang-pages-login",
>       "lang-pages-register",
>       "lang-pages-verification",
>       "lang-pages-Page404",
>       "lang-pages-Page500"
>     ]
>   }
> });

After that VUEX shows under auth.payload an accessToken, my user and strategy='local'.
Anyway, when trying to read data from a service having a hook authenticate('jwt') I get a Not Authenticated error. 
Using Postman with my jwt accessToken works, so it still seems to be a misconfigured environment ;-(

**Comment by marshallswain** [comment]
I'm glad you figured this out.  If you see a place to update the docs, that would be very much appreciated.
