### ISSUE TITLE
Oh no!  feathers-vuex.feathers-plus.com’s server IP address could not be found.

### ISSUE THREAD

**Issue by corepay** [feathersjs-ecosystem/feathers-vuex#338]
![image](https://user-images.githubusercontent.com/48992923/67964942-85a16c80-fbd7-11e9-99d0-1ff7ebd301fc.png)

**Comment by apmcodes** [comment]
Its down ...

**Comment by corepay** [comment]
> Its down ...

yes ok course - only reported in the event Marshall or team were not aware so they would get an email notification.....

**Comment by spectrolite** [comment]
For those in dire need of v2 docs, their markdown version is still available under docs in this same repo.

**Comment by marshallswain** [comment]
Sorry that this has been down.  I posted in the Slack channel: https://feathersjs.slack.com/archives/C11VCU0Q4/p1572496786058100.

I thought it was a DNS propagation issue, but it seems to be more.  I can't get the URL to work with Netlify now that the repo has been transferred back to the `feathersjs-ecosystem` org.  I'm going to just change the official URL to https://feathers-vuex.netlify.com.
