### ISSUE TITLE
Reauth when tab reload

### ISSUE THREAD

**Issue by nvthuong1996** [feathersjs-ecosystem/feathers-vuex#340]
I use version 2.0.5 feathers-vuex in Nuxt. After I finished logging in and trying to reload the page I found that I was no longer logged in. Even if the token is still stored in local storage. That's ridiculous.

**Comment by J3m5** [comment]
You are still "logged in" because the JWT is still valid and stored in the localStorage.
You need to verify in the router beforeEach if you are authenticated by calling  the authenticate action of the auth module.

With something like that:

```js
router.beforeEach((to, from, next) => {
  if (to.meta.requiresAuth) {

    if (!store.state.auth.user) {
      api.reAuthenticate().then(() => {
        next()
      }).catch(() => {
        next({
          name: "login"
        });
      });
```

Feathers-Vuex has nothing to do with the way you handle you routing and authorization process.

**Comment by marshallswain** [comment]
@nvthuong1996, While I totally comprehend why you would say it is ridiculous for your use case, this behavior is tightly coupled to your app's business logic.  @J3m5 has presented one way to accomplish what you're after.

> Feathers-Vuex has nothing to do with the way you handle your routing and authorization process.

This is accurate.

**Comment by andrewharvey** [comment]
@J3m5 any hints on where to put that code snippet? I'm using https://vuex.feathersjs.com/common-patterns.html#full-nuxt-example and the vue router is all handled transparently by nuxt.

**Comment by J3m5** [comment]
@andrewharvey 
If you are using nuxt then you should follow the [feathers-vuex documentation](https://vuex.feathersjs.com/nuxt.html#nuxt).
The logic is basically the same, it's just adapted to the nuxt API.
