### ISSUE TITLE
find action with $select returns all fields

### ISSUE THREAD

**Issue by spectrolite** [feathersjs-ecosystem/feathers-vuex#345]
### Steps to reproduce
use find on model with a query specifying a $select
notice that the response still contains all fields

### Expected behavior
Should return only selected fields

### Actual behavior
Returns all fields

### System configuration
feathers-vuex version 2.0.4
+ feathers-mongoose

**Comment by marshallswain** [comment]
@spectrolite, I already had tests for the `find` getter, but didn't have any for the `find` action.  I've added tests for the `find` action in the above-referenced commit.  They are passing without making any further changes.  If you provide some more details on how to duplicate this scenario then I'll be able to investigate more.

**Comment by marshallswain** [comment]
I'm glad to fix this if you can give me a reproducible scenario.  Please reopen when you have time.

**Comment by StefanGhiban** [comment]
I am encountering the same issue. Even though I have a $select, all fields are returned. This is happening in feathers-vuex: 3.16.0 with feathers-knex: 8.0.1

**Comment by marshallswain** [comment]
Looking into this further, $select cannot be supported on the client.  It's only used to limit the attributes that are loaded from the server.  The client should always return all attributes of every instance.
