### ISSUE TITLE
Not working with @feathersjs 4.3.10

### ISSUE THREAD

**Issue by calvinmuller** [feathersjs-ecosystem/feathers-vuex#348]
### Steps to reproduce
`feathers-client.js`
```
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'
import auth from '@feathersjs/authentication-client'
import io from 'socket.io-client'
import { iff, discard } from 'feathers-hooks-common'
import feathersVuex from 'feathers-vuex'
import { CookieStorage } from 'cookie-storage'

const storage = new CookieStorage();
const socket = io('http://localhost:3000', {transports: ['websocket']})

const feathersClient = feathers()
  .configure(socketio(socket))
  .configure(auth({ storage }));

export default feathersClient

// Setting up feathers-vuex
const { makeServicePlugin, makeAuthPlugin, BaseModel, models } = feathersVuex(
  feathersClient,
  {
    serverAlias: 'api', // optional for working with multiple APIs (this is the default value)
    idField: 'id', // Must match the id field in your database table/collection
    whitelist: ['$regex', '$options']
  }
)

export { makeAuthPlugin, makeServicePlugin, BaseModel, models }

```
`store/index.js`
```
import feathersClient from '../feathers-client';
import feathersVuex, { initAuth } from 'feathers-vuex';

const { makeServicePlugin, makeAuthPlugin } = feathersVuex(feathersClient, { idField: 'id' });

export const state = () => ({});
export const mutations = {};

export const actions = {
  nuxtServerInit({ commit, dispatch }, { req }) {
    return initAuth({
      commit,
      dispatch,
      req,
      moduleName: 'auth',
      cookieName: 'feathers-jwt'
    })
  }
};

export const plugins = [
  makeAuthPlugin({
    userService: 'users'
  })
];

```

### Expected behavior
It should work

### Actual behavior
```
"export 'default' (imported as 'dbCommons') was not found in '@feathersjs/adapter-commons'   
```

Output from browser upon reload is
```
TypeError
Cannot destructure property `filterQuery` of 'undefined' or 'null'.

import { _ } from '@feathersjs/commons'
import dbCommons from '@feathersjs/adapter-commons'
import { globalModels as models } from './global-models'
import _get from 'lodash/get'
import _omit from 'lodash/omit'
const { filterQuery, sorter, select } = dbCommons
const FILTERS = ['$sort', '$limit', '$skip', '$select']
const OPERATORS = ['$in', '$nin', '$lt', '$lte', '$gt', '$gte', '$ne', '$or']
const additionalOperators = ['$elemMatch']
const defaultOps = FILTERS.concat(OPERATORS).concat(additionalOperators)
export default function makeServiceGetters() {
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
    "@feathersjs/authentication": "^4.3.10",
    "@feathersjs/authentication-client": "^4.3.10",
    "@feathersjs/authentication-local": "^4.3.10",
    "@feathersjs/authentication-oauth": "^4.3.10",
    "@feathersjs/configuration": "^4.3.10",
    "@feathersjs/errors": "^4.3.10",
    "@feathersjs/express": "^4.3.10",
    "@feathersjs/feathers": "^4.3.10",
    "@feathersjs/socketio": "^4.3.10",
    "@feathersjs/socketio-client": "^4.3.10",
    "@feathersjs/transport-commons": "^4.3.10",
    "@feathersjs/adapter-commons": "^4.3.10",
```

**NodeJS version**:
v11.4.0

**Operating System**:
MacOSX

**Browser Version**:
Chrome

**React Native Version**:

**Module Loader**:
NUXT

**Comment by marshallswain** [comment]
This looks like an error that was fixed a few versions back.  Could you `npm i feathers-vuex@latest` or `yarn add feathers-vuex@latest` and try again?

**Comment by calvinmuller** [comment]
I'm currently using "feathers-vuex": "^2.2.3" - I saw this issue #247 but as it's old and im on the latest version - I assumed its something new. :/

**Comment by marshallswain** [comment]
Hmm... Everything looks fine in the feathers-vuex node_modules folder. The `adapter-commons` package definitely has an exported object, so there's not really a good reason for it to be undefined in your setup:

![Screen Shot 2019-11-11 at 1 29 15 PM](https://user-images.githubusercontent.com/128857/68618749-4a305900-0487-11ea-9c28-fcc2316f769f.jpg)

Try `npm cache clean` or `yarn cache clean`, maybe?

**Comment by marshallswain** [comment]
Ah.  Nope.  Something's definitely off in the repo, this is the latest code on Github: https://github.com/feathersjs/feathers/blob/master/packages/adapter-commons/src/index.ts#L4

This is for me to fix.

**Comment by calvinmuller** [comment]
nah - same things.

Could this not maybe be causing some issues?
https://github.com/feathersjs-ecosystem/feathers-vuex/blob/fbde9705ce6cb09d243b7b9b65d1982df9c70644/package.json#L101

**Comment by calvinmuller** [comment]
Ah i just saw your comment now - awesome man! thanks.

**Comment by marshallswain** [comment]
Ok.  Try installing @latest again and let me know how it goes.

**Comment by marshallswain** [comment]
I've updated all of the dependencies and enabled Greenkeeper, so this should now be resolved.  Feel free to reopen if you find there's still an issue.

**Comment by calvinmuller** [comment]
Sorted, thanks @marshallswain !
