### ISSUE TITLE
After migration have error

### ISSUE THREAD

**Issue by andysay** [feathersjs-ecosystem/feathers-vuex#357]
im  try use on v4 this import feathersVuex, { initAuth } from 'feathers-vuex';
 but get 

import FeathersVuexFind from './FeathersVuexFind'
  ^^^^^^
  
  SyntaxError: Cannot use import statement outside a module

on v3 works fine! 

node v12

**Comment by marshallswain** [comment]
I've not seen this one before, but it seems like it's related to a build system.  Feathers-Vuex 2.x is published as an ES6 module, which means you'll need to assure that your build system transpiles it in node_modules.  View the first page of the docs to see how to enable this in a few common environments.

**Comment by andysay** [comment]
okay , im add in my nuxt.config.js 

    transpile: ['feathers-vuex'],

, and now i have

 WARN  Compiled with 3 warnings                                                                                                                                       friendly-errors 09:53:46


 WARN  in ./node_modules/feathers-vuex/dist/utils.js                                                                                                                  friendly-errors 09:53:46

"export 'default' (imported as '_isObject') was not found in 'lodash/isObject'                                                                                        friendly-errors 09:53:46
                                                                                                                                                                      friendly-errors 09:53:46

 WARN  in ./node_modules/feathers-vuex/dist/utils.js                                                                                                                  friendly-errors 09:53:46

"export 'default' (imported as '_trim') was not found in 'lodash/trim'                                                                                                friendly-errors 09:53:46

**Comment by andysay** [comment]
re install fix it..
