### ISSUE TITLE
Cannot read property 'verifyJWT' of undefined

### ISSUE THREAD

**Issue by andysay** [feathersjs-ecosystem/feathers-vuex#360]
Hello again, i'm have latest  version feathersjs and feathers-vuex, when i'm login from my frontend cookie set 'feathers-jwt' : Cannot read property 'verifyJWT' of undefined

why ?  login work corect , token back fine from server

but in cookie not set .

my login code 

```
  login({
    commit
  }, {
    email,
    password
  }) {
    return feathersClient.authenticate({
        strategy: 'local',
        email,
        password
      })
      .then(async response =>  {
 
        return feathersClient.passport.verifyJWT(response.accessToken)
      })
      .then((payload) => {
        return feathersClient.service('users').get(payload.userId)
      })
      .then((user) => {
       feathersClient.set('user', user);
       commit('SET_USER', user);
       return feathersClient.passport.getJWT();
      }).catch(function (error) {
        return error;
      });
  },
```

**Comment by marshallswain** [comment]
Your login code is outdated, and completely unneeded. All of that functionality is already handled inside feathers-vuex once you add a `userService: 'users'` attribute to your auth plugin options.  Instead of calling `feathersClient.authenticate`, you should just be dispatching the `auth/authenticate` action.  The rest is done for you.

```js
// inside your component
{
  name: 'MyLoginForm',
  data: {
    email: '',
    password: '',
  },
  methods: {
    login() {
      this.$store.dispatch('auth/authenticate', {
        strategy: 'local',
        email: this.email,
        password: this.password
      }).then(this.handleLogin)
    },
    handleLogin(response) {
      console.log(response)
    }
  }
}
```

**Comment by andysay** [comment]
okay i'm change to this , and have now in my cookie content object Object

**Comment by andysay** [comment]
after login have correct record
<img width="792" alt="Снимок экрана 2019-11-17 в 12 59 37" src="https://user-images.githubusercontent.com/5610952/69005983-52cad880-093a-11ea-94ca-42f99a352616.png">

after change feather-jwt was change on this

<img width="783" alt="Снимок экрана 2019-11-17 в 13 00 23" src="https://user-images.githubusercontent.com/5610952/69005987-5fe7c780-093a-11ea-8bf4-17a82c4ee510.png">

**Comment by marshallswain** [comment]
Set a break points in the auth actions file to see why it's being set as an object.

**Comment by marshallswain** [comment]
Actually, I suspect that you have some route-handling logic that's doing this, so the above breakpoint probably won't help any.

**Comment by andysay** [comment]
> Actually, I suspect that you have some route-handling logic that's doing this, so the above breakpoint probably won't help any.

im comment route section, look cookie and see object object at once .. its not problem with route , application set cookie 2 times. 
im create new cookie ' key : token ' , thats work fine , but feathers-jwt works wrong

**Comment by andysay** [comment]
> Set a break points in the auth actions file to see why it's being set as an object.
> 
> In the Chrome devtools, open the source panel then press ⌘+p or probably control+p if you're on a non-mac machine. Type actions.js and look for the auth actions. Then you can set a break point in the auth response handler. This could be a bug.

need look node_modules/feathers-vuex/dist/auth-module/auth-module.actions.js ?
