### ISSUE TITLE
Feathers Vuex, hooks and events different behavior in v4?

### ISSUE THREAD

**Issue by klaus1978** [feathersjs-ecosystem/feathers-vuex#367]
### Overview

Hi all,
I currently wonder how hooks and events work together.
I have following setting:
Client:
>      feathers-vuex: v2.0.5
>     "@feathersjs/authentication-client": "^4.3.11",
>     "@feathersjs/feathers": "^4.3.11",
>     "@feathersjs/socketio-client": "^4.3.11",

Server:
>     "@feathersjs/authentication": "^4.3.11",
>     "@feathersjs/authentication-local": "^4.3.11",
>     "@feathersjs/authentication-oauth": "^4.3.11",
>     "@feathersjs/configuration": "^4.3.11",
>     "@feathersjs/errors": "^4.3.11",
>     "@feathersjs/express": "^4.3.11",
>     "@feathersjs/feathers": "^4.3.11",
>     "@feathersjs/socketio": "^4.3.11",

my app has a profile service which keeps the profile information of the authenticated user and for sure should not be visible to other authenticated users.
In v3 I created a restrictToOwner hook and this seemed to be enough to secure my app (not sure why, but it worked)
Now in v4, I see following behavior:
user1 connects and can see his profile setting (also in VUEX DEV tools 1 entry in ids)
user2 connects and can see his profile setting (also in VUEX DEV tools 1 entry in ids)

When user1 changes the profile settings and saves it, I see in the app for user 2 that the vuex store got updated and now the profile information of user 1 is also available, which is pretty bad...

This is the hook config: (btw: I also updated restrictToOwner to setField so do not wonder here..)
```
const {
  authenticate
} = require('@feathersjs/authentication').hooks;
const {
  setField,
  // associateCurrentUser
} = require('feathers-authentication-hooks');
const checkPermissions = require('feathers-permissions');
const commonHooks = require('feathers-hooks-common');

const restrict = [
  authenticate('jwt'),
  checkPermissions({
    roles: ['admin'],
    error: false
  }),
  commonHooks.iff(context => !context.params.permitted,
    setField({
      from: 'params.user._id',
      as: 'params.query._id'
    }),
    // restrictToOwner({
    //   idField: '_id',
    //   ownerField: '_id'
    // })
  ),
];

module.exports = {
  before: {
    all: [authenticate('jwt')],
    find: [...restrict],
    get: [...restrict],
    create: [
      setField({
        from: 'params.user._id',
        as: 'data._id'
      })
      // associateCurrentUser({
      // idField: '_id',
      // as: '_id'
      // })
    ],
    update: [...restrict, ],
    patch: [...restrict, ],
    remove: []
  },
```

So my guess is, that hooks (new in v4?) have no influence on creating events? If my user1 updates his data, an event is created and sent to all other authenticated users, "restrictToOwner" has no influence here?
--> I adapted my channels.js file like in the docs:
 I added:
```
app.channel(`userIds/${connection.user._id}`).join(connection);
```
to create a channel only for my connected user

and below

> app.publish((data, hook) => {
>     // e.g. to publish all service events to all authenticated users use
>     return app.channel('authenticated');
>   });

 I added this here:
```
  app.service('profile').publish(profile => {
    return app.channel(`userIds/${profile._id}`);
  });
```

this now did the trick: user2 does not get the update event and thus also his VUEX Store is not being updated by user1's data.

BUT this confuses me at all: Why is it working now? There is still the part active that publishes all service events to all authenticated users? So my second change should not have an effect?

I also cannot see, why in v3 all seemed to work out of the box (even without event handling...)?
Any help or general explanations would be highly welcome.

KR Klaus

**Comment by marshallswain** [comment]
> I also cannot see, why in v3 all seemed to work out of the box (even without event handling...)?  Any help or general explanations would be highly welcome.

I don't know why it worked before, but your solution of modifying the channels for the `profile` service is the correct solution for V4.

> There is still the part active that publishes all service events to all authenticated users?

Maybe @daffl can explain.  Are you saying that you have the following channel setup?

```js
app.publish((data, hook) => {
   return app.channel('authenticated')
})
app.service('profile').publish(profile => {
   return app.channel(`userIds/${profile._id}`)
})
```

And that with the above setup you are seeing that authenticated users DO NOT receive the vent?

This isn't a feathers-vuex issue at all, but I'll leave this open until we get some clarity because I might have something to learn from this, too.

**Comment by klaus1978** [comment]
Hi Marshall,
many thanks for taking the time to also think about that issue.
Yes, this was my channel setup:
```
app.publish((data, hook) => {
console.log('triggered');
   return app.channel('authenticated')
})
app.service('profile').publish(profile => {
   return app.channel(`userIds/${profile._id}`)
})
```
I now disabled the first part for 'authenticated', because I also saw in user2's VUEX store also user1 in the USERS section in the moment when user1 logged in as well...
So this code section was definitely still triggered, although I still could not find out when it was triggered; in the meantime I was suggesting it just triggers for updates, but still not sure if this is the truth...
Best Klaus

**Comment by marshallswain** [comment]
Ok. This makes more sense because to my knowledge both the app-level publish and service-level publish should take place.  This is expected behavior.
