### ISSUE TITLE
how to properly delete account

### ISSUE THREAD

**Issue by eikaramba** [feathersjs-ecosystem/feathers-vuex#376]
I recently had problems implementing a "delete my account" functionality and wanted to share my findings resp. ask what the proper way of doing so would be in your opinion:

Removing an account and then logging out does not work as the logout method would fail with "user not found" (makes sense i guess). Unfortunately just removing the user is not enough as the feathers jwt token is still in the browser storage.

So what worked for me was this:
```
await store.dispatch("users/remove", this.user._id); //remove user
document.cookie = `feathers-jwt=;expires=Thu, 01 Jan 1970 00:00:01 GMT;`; //delete cookie, yes this is how you delete a cookie
await feathersClient.get('storage').removeItem("feathers-jwt"); // delete local storage entry
```

Hope this helps someone :)

**Comment by marshallswain** [comment]
@eikaramba thanks for creating this issue.  It'll be much easier to find a solution, now.  This might make for a good recipe on the FeathersJS docs, too.
