### ISSUE TITLE
Doc question on instanceDefaults and setupInstance

### ISSUE THREAD

**Issue by bzd2000** [feathersjs-ecosystem/feathers-vuex#382]
### Steps to reproduce

First question, I don't understand the difference between instanceDefaults and setupInstance.
Seems to be the same definition for both function.

Secondly,  How can I pass a variable when creating a new instance

for example
```
const {TimeEntry} = this.$FeathersVuex.api;
return new TimeEntry({projectId: someId});
```

Can I pass the projectId like this?  What should I do then in the instanceDefaults and setupInstance?

I currently solved it like this, but maybe there is a better way
```
 const {TimeEntry} = this.$FeathersVuex.api;
 let timeEntry = new TimeEntry();
 timeEntry.projectId = projectId;
 return timeEntry;
```
Thx,
Filip.

**Comment by marshallswain** [comment]
## Difference between `instanceDefaults` and `setupInstance`

You are correct that they use the same definition for both.  The difference is in the order in which they are applied.  

1. When you provide data to a model class, like `TimeInstance` in your case, the data that you pass to the constructor is merged on top of the `instanceDefaults` return value, first.  If you don't provide any values when creating a new instance, you'll get an object with these default values.
2. The result of the previous step is then passed to `setupInstance`.  All default values have been applied.  You can conditionally overwrite or modify default values, here based on other attributes.  You can modify the object and the return value will become the final instance data.  

So, the `instanceDefaults` should basically ONLY be used to return default values for a new instance.  The `setupInstance` method should generally be used for everything else. (defining model relationships, converting date strings and timestamps into Date objects, etc.)


They may seem similar and redundant, but they provide necessary flexibility.

## Both examples that you've provided should produce the same result.

```js
const { TimeEntry } = this.$FeathersVuex.api

const timeEntry = new TimeEntry({ projectId: 5 })

const timeEntry2 = new TimeEntry({})
timeEntry2.projectId = 5
```

Both of these produce the same result.

**Comment by bzd2000** [comment]
ok thx!

**Comment by marshallswain** [comment]
I'm going to leave this open and add this info to the docs.  Thanks!
