### ISSUE TITLE
Improved perceived performance with service workers

### ISSUE THREAD

**Issue by marshallswain** [feathersjs-ecosystem/feathers-vuex#391]
It's all explained in this article: https://logaretm.com/blog/2019-12-21-vuex-off-mainthread/

Should I bake this into feathers-vuex or create it as a separate package?

**Comment by Bomberus** [comment]
Short question, does using web workers really improve the performance for vuex? 

In the end after calculating the new state in a web worker you still need to merge this state with your main thread, which can still cause some micro freezes. 

Usually vuex calculations are not heavily cpu intensive, aren‘t we just adding more overhead?

In this blog entry, the example was using a pi calculation, I doubt this is  a common requirement.

**Comment by marshallswain** [comment]
There would only be a potential increase in perceived performance.  I'm going to experiment with it to find out for certain.

**Comment by marshallswain** [comment]
I'm not going to get to this for a while, if ever.  Closing for now.
