### ISSUE TITLE
[Bug] MakeFindMixin: local option doesn't works as specified in the docs

### ISSUE THREAD

**Issue by J3m5** [feathersjs-ecosystem/feathers-vuex#394]
### Steps to reproduce
In a template, add a makeFindMixin like this: 

```js
mixins:[ makeFindMixin({ service: "yourServiceName", local: true, params: () => ({}) }) ]
```

### Expected behavior
The mixin should not make a request to the API server but use the params to pull data from the local store as stated in the docs.

> local {Boolean|String|Function} - when true, will only use the params prop to pull data from the local Vuex store. It will disable queries to the API server. The value of local will override queryWhen. Default:false

### Actual behavior
The API request is sent, the local option is not respected.
If you omit the params option, the API request is not sent but the store getter returns nothing.

### What cause this behavior
In the created lifeCycle event, on [this line](https://github.com/feathersjs-ecosystem/feathers-vuex/blob/98b3f796050340e8afdeba4183a9685367cd8fbb/src/make-find-mixin.ts#L245) , only
the presence of the params and fetchParams options are checked in order to make the API request.

If they are not present, the absence of the local option is used to log a message.

### How to fix it
Check the truthiness of the local option to send the API request or not.
I can submit a PR if everything is ok.

### System configuration

**Module versions**: 3.2.1

**NodeJS version**: 12.4.0

**Operating System**: Linux

**Browser Version**: Chromium 79

**Module Loader**: Webpack

**Comment by marshallswain** [comment]
The `local` option is definitely being checked here: https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/src/make-find-mixin.ts#L182

I don't usually pass the params like in your example, above, but that should affect the `local: true`.

**Comment by J3m5** [comment]
Ok, I'll keep looking.

**Comment by J3m5** [comment]
So, I found the problem.
I added the find method with the `mapMutations` helper and it conflicted with the find method added by the mixin.

This (I don't know why) trigger the find call automatically.
So the problem was not the local option.

But I still think that there should be a option that would prevent the find/get call on the created event but that would permit the use of the find method after that.

Because currently it disable the find method completely, so we need to add the find/get method and be careful to not rename it with the same name as the one of the mixin.

The solution would be to make the find call conditionnaly on the created event rather than in the find method itself.

And I don't see the usecase of having a disabled find method, if you don't want it, don't use it, it is added on the component anyway.

The solution would be to add another option like `fetchOnCreated` that would be true by default but I think that there are already enough mixin options.

But maybe it could be handled on the user side, as I just see, the local property is set on the `data` option, so it can be changed on the mounted event (I tested it and it works).

What do you think?

**Comment by marshallswain** [comment]
I think that we can probably move the check for `isLocal` inside the `makeFindMixin` into the watcher.  That way you'll be able to use the find method that it provides and not need to separately map it.

**Comment by J3m5** [comment]
Do you mean [here](https://github.com/feathersjs-ecosystem/feathers-vuex/blob/f94277e7e6d36571201deb086560a01f053d5b51/src/make-find-mixin.ts#L257) ?

**Comment by marshallswain** [comment]
Yes.  If isLocal is true there, we can do an early return.  Then remove the check in the find action.

**Comment by marshallswain** [comment]
https://github.com/feathersjs-ecosystem/feathers-vuex/blob/f94277e7e6d36571201deb086560a01f053d5b51/src/make-find-mixin.ts
That check can be removed if we move it to the watcher.

**Comment by J3m5** [comment]
OK but why in the watcher? 
We could put it simply at the beginning of the created event, no? What would be the difference?

Correct me if I'm wrong but isn't the purpose of the created event to only to make the find request when it is triggered and when the params change?

In that case, we could even add the created property conditionally, it would make the mixin lighter.

**Comment by marshallswain** [comment]
That is a very good point.  Nice job looking even further ahead.  That will be a great optimization.

**Comment by J3m5** [comment]
Ok, nice, I'll create a PR when I'll get some time!
