### ISSUE TITLE
[Sponsor] Add tiers with a lower price

### ISSUE THREAD

**Issue by J3m5** [feathersjs-ecosystem/feathers-vuex#395]
Adding tiers with a lower price would be nice for peoples who would like to contribute but can't afford it with the actual one.

**Comment by marshallswain** [comment]
I added a few more tiers.  Thanks again!

![Screen Shot 2019-12-24 at 12 15 01 AM](https://user-images.githubusercontent.com/128857/71399921-7260bb00-25e2-11ea-8025-4fb3679bdd86.jpg)

**Comment by J3m5** [comment]
Great! :+1:
