### ISSUE TITLE
Whitelisted operators not allowed despite whitelisting

### ISSUE THREAD

**Issue by Ziao** [feathersjs-ecosystem/feathers-vuex#411]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

I whitelisted `$iLike` using the whitelist option while initialising feathersVuex:
```js
const { makeServicePlugin, makeAuthPlugin, BaseModel, models, FeathersVuex } = feathersVuex(feathersClient, {
    whitelist: ['$regex', '$options', '$iLike', '$like'],
});
```

### Actual behavior

When trying to use one of these query operators using the `useFind()` composable, the following error is thrown: `[Vue warn]: Error in render: "Error: Unknown operation $iLike"`

```js
 const findData = useFind({
            model: models.api.Project,
            params: { // actually a computed() from elsewhere
                        query: {
                                    name: { $iLike: '%foobar%' }
                        }
            } 
});
```

### System configuration

Using the new composition API

**Module versions** (especially the part that's not working):
Vue 2.6.10
Composition-api 0.3.4
Feathers-vuex 3.2.1
Feathers (client) 4.4.3

**NodeJS version**:
12.0.0

**Operating System**:
OSX 10.15.1

**Browser Version**:

Latest Chrome at the time of writing

**Module Loader**:

**Comment by J3m5** [comment]
I assume that those operators are meant to be sent to the server, so they should be added in the `paramsForServer` option on the [global configuration](https://vuex.feathersjs.com/getting-started.html#global-configuration) or [service configuration](https://vuex.feathersjs.com/service-plugin.html#configuration).

Theses operators will be sent to the server but ignored by the store getter.

**Comment by Ziao** [comment]
@J3m5  Thanks for pointing me in the right direction!
I've instead specified those parameters to `fetchParams` as per the TS definitions, but when I do that (no matter which fields I specify), no parameters are sent to the server whatsoever, according to the chrome inspector. Would you have any idea why that would be? If helpful, I can provide some sample code.

**Comment by J3m5** [comment]
Sharing the code of the template would help, yes.

**Comment by J3m5** [comment]
Any news @ziao?

**Comment by markwcollins** [comment]
This definitely helped me!

**Comment by yohane55** [comment]
I think this a bug in `useFind` of composition api. In my old project with `...mapActions` & `...mapGetter`, it works without whitelisting or other configuration. @marshallswain will you work on to fix this or should we give up on composition api for now?

**Comment by jonascript** [comment]
I'm unable to get this to work with $regex, $like or $iLike as well using feathers-sequelize despite whitelisting params paramsForServer. 

It does work if I use the dispatch (non composition api) method ```$store.dispatch('myservice/find', { query: { $iLike: '%foo%'} })``` This means you cannot use feathers-sequelize with composition api if you want to do special operator queries.
