### ISSUE TITLE
"useFind" does not filter items if params is non reactive object

### ISSUE THREAD

**Issue by agte** [feathersjs-ecosystem/feathers-vuex#413]
I tried to make a filtered list. I passed a simple object to "useFind".
```
useFind({
  model: MyModel,
  params: {
    query: { status: 'draft' }
  }
})
```
Network request is correct - it uses my params and gets a correct response. But rendered list is not correct. It ignores params and shows all data from the store.

Then a tried to pass not a simple object, but a Ref.
```
useFind({
  model: MyModel,
  params: ref({
    query: { status: 'draft' }
  })
})
```
And it works fine.

I think the problem is located here: https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/src/useFind.ts#L98-L100
```
      const getterParams: Params = isRef(params)
        ? Object.assign({}, params.value)
        : { params }
```
If params is not a Ref, then you create a wrapper object. So instead of just { query: {} } you create { params: { query: {} } }. Then "find" getter can not find a "query" property in such params, so it does not apply filters and returns all data from the store.
https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/src/service-module/service-module.getters.ts#L30

**Comment by marshallswain** [comment]
Ah yep.  I believe your words are accurate.  If you remove the wrapper object, does it behave as expected?  I won't be able to get to this until next week, but your report will be beneficial for getting it fixed quicker.

**Comment by J3m5** [comment]
A PR is almost finished, I just need to test it but I'm facing a bug now.

When I install feathers-vuex from my github repo and build it in a project, it complains about a missing type on the EventEmitter package.
But it doesn't when I build it directly in the fork directory...
