### ISSUE TITLE
Request Feature -  Parameter to reload the page when the logout function is called

### ISSUE THREAD

**Issue by juancampuzano** [feathersjs-ecosystem/feathers-vuex#416]
I am having a problem due to the silver solution in the following issue: https://github.com/feathersjs-ecosystem/feathers-vuex/issues/10

When I use the logout feathers function and then reload the page it seems that I was loading the login page twice.

¿It is possible to add a parameter to the navout logout function?. So if that parameter is true, reload the page!

**Comment by marshallswain** [comment]
Is the solution you are currently using?

```js
logout()
router.push('/login')
setTimeout(() => {
   window.location.reload()
}, 20)
```

**Comment by marshallswain** [comment]
I'm not sure what code you're using for this issue, but the above solution works in my apps and doesn't show the login page twice.  Please reopen if you feel like there's something more to talk about.
