### ISSUE TITLE
empty pageInfo in query using $and or $or

### ISSUE THREAD

**Issue by xtrial** [feathersjs-ecosystem/feathers-vuex#423]
### Steps to reproduce

i'm following the renderless data component docs example using normal query like:
`{ $limit, $skip, [fieldname]: { $search: string } }`
work just fine.

but, if i try
`{ $limit, $skip, $or: [ { [fieldname]: { $search: string } } ] }`
then my client get the data but pageInfo is empty

i don't know if i miss something or there is something wrong in my code & setup

### Expected behavior
working just fine

### Actual behavior
no pageInfo

### System configuration

**Client Package**
```
    "@feathersjs/feathers": "^4.5.1",
    "feathers-hooks-common": "^5.0.2",
    "feathers-vuex": "^3.5.5",
```

**Server Package**
```
    "@feathersjs/express": "^4.5.1",
    "@feathersjs/feathers": "^4.5.1",
```

**Comment by marshallswain** [comment]
Thanks for reporting this.  This is probably related to https://github.com/feathersjs-ecosystem/feathers-vuex/issues/364
