### ISSUE TITLE
Extending the default store for all services

### ISSUE THREAD

**Issue by kshitizshankar** [feathersjs-ecosystem/feathers-vuex#428]
Hi,

I am trying to add a few properties to the store of all services. This includes some state, getters, mutations etc.

How exactly are we supposed to do this?

In my setup, I just created a global store object like - 
```
const mycustomstore = {
    state: { newProperty: 1 },
    getters: { getNewProperty(state) { return state.newProperty },
    ....
}
```
which I am then passing to the setup feathers-vuex call 
```
const {
  makeServicePlugin,
  makeAuthPlugin,
  BaseModel,
  models,
  clients,
  FeathersVuex
} = feathersVuex(feathersClient, {
  serverAlias: 'newAPI',
  idField: '_id',
  skipRequestIfExists: true,
  ...mycustomstore
})
```
This seemed to do the job for the time being, but I ran into the issue where when I create custom store properties inside the individual service - It overrides the global store addons.

After some digging, I found that the issue was in how the makeServicePlugin handles the options.
```
return function makeServicePlugin(config) {
    const options = Object.assign({}, defaults, globalOptions, config)
    ....
```

So coming to the real question - is there a reason to not merge the options?
Something like -
```
return function makeServicePlugin(config) {
    const options = lodash.merge({}, defaults, globalOptions, config)
    ....
```
If not, I can just create a wrapper that does (something like a customMakeServicePlugin, similar to the customBaseModel).

Is there something that I might be missing here or is there a different recommended way of achieving this use case [global custom store to all services + service-specific store]?

Thanks!

**Comment by marshallswain** [comment]
src/store/defaults.js
```
export const state = {
  attr1: true,
  attr2: true
}
export const getters = {}
export const mutations = {}
export const actions = {}
```

src/store/services/service-one.js
```js
import { state, getters, mutations, actions } from '../defaults.js`

makeServicePlugin({
  state: {
    ...state,
    customAttr1: true
  },
  getters: {
    ...getters,
    customGetter(){}
  },
  mutations: {
    ...mutations,
    customMutation(){}
  }
  actions: {
    ...actions,
    customAction(){}
  }
})
```

**Comment by marshallswain** [comment]
Closing, since I think the above is the best solution for this.  Feel free to comment, reopen if required.
