### ISSUE TITLE
How do I do associations between tables?

### ISSUE THREAD

**Issue by juancampuzano** [feathersjs-ecosystem/feathers-vuex#429]
Is it possible do associations between tables using feather vuex as appears in https://docs.feathersjs.com/help/faq.html#how-do-i-do-associations

Note: I want to make a join between two tables

**Comment by marshallswain** [comment]
Feathers-Vuex can handle the associations by making sure the populated data from a single service call gets split out into the correct service stores, but it doesn't actually populate anything for you.  I'll be sharing a project that I built which I consider to be the simplest way to setup these relationships in a scalable and high-performance way.  I built it for my feathers-vuex projects, but it will work with any front end, so it will be a separate project.  I just need to finish the docs. 

In the meantime, look into feathers-shallow-populate.  It's about to come out of deprecation.  ;)

**Comment by juancampuzano** [comment]
@marshallswain any update about the separate project.

**Comment by marshallswain** [comment]
@juancampuzano hot off the press: https://feathers-graph-populate.netlify.com/

**Comment by juancampuzano** [comment]
Thank you @marshallswain!
