### ISSUE TITLE
Integration with vuex-persistedstate creates error

### ISSUE THREAD

**Issue by laurensiusadi** [feathersjs-ecosystem/feathers-vuex#439]
### Steps to reproduce

1. Clone https://github.com/laurensiusadi/feathers-vuex-persistedstate-problem (feathers-vuex-chat with vuex-persistedstate installed)
2. Run repo as it should with `feathers-chat` server too
3. Sign up then sign in
4. Send a chat
5. Refresh browser (a chat sent earlier is loaded from localstorage)
6. Try hitting delete button (uses `message.remove`)
![image](https://user-images.githubusercontent.com/5661040/75675282-716e9880-5cb9-11ea-87fd-b26650a92b4d.png)
7. It will throw error
![image](https://user-images.githubusercontent.com/5661040/75675104-0de46b00-5cb9-11ea-9fe2-eb25644f434c.png)
8. Now try send new chat
9. Click delete button immediately without refresh in between
10. Chat removed without error

### Expected behavior
Able to delete record using `message.remove()`

### Actual behavior
Error thrown with data from localstorage

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 12.16.0

**Operating System**: Windows 10

**Browser Version**: Opera 66, Firefox 73

### Additional info
Error behaviour was found initially on a private repo, with `vuex-persistedstate` and `vuex-persist` using localstorage and localforage (async) both tested giving same error for all record methods (patch, remove). Turns out error is able to be duplicated using `feathers-vuex-chat`.

**Comment by laurensiusadi** [comment]
The problem was object rehydrated from localstorage uses `JSON.parse()` so it becomes plain object instead of a model object.

Solution:
```javascript
const persistPlugin = (namespace, paths) =>
  createPersistedState({
    key: namespace,
    paths: paths,
    rehydrated: store => {
      const state = store.state[namespace]
      const commit = store.commit
      Object.keys(state.keyedById).forEach(id => {
        const record = state.keyedById[id]
        commit(`${namespace}/removeItem`, record)
        commit(`${namespace}/addItem`, record)
      })
    }
  })
```

**Comment by marshallswain** [comment]
It might also be possible to use the `hydrateAPI` method.  The docs are currently missing the API signature for it, but you can see it in the example code.  It basically does what you've done above.

**Comment by laurensiusadi** [comment]
@marshallswain Yes, I'm copying the code from `hydrateAPI`, but since I use multiple store plugins, I decide to use that code so I don't call `hydrateAPI` multiple times.
