### ISSUE TITLE
Demo page is broken

### ISSUE THREAD

**Issue by tvld** [feathersjs-ecosystem/feathers-vuex#441]
click on demo link gives me:
![Screenshot from 2020-03-05 10-01-40](https://user-images.githubusercontent.com/986182/75964999-76edfd80-5ec8-11ea-8a57-9bf0e0d61ed0.png)

**Comment by marshallswain** [comment]
What link leads to this demo?

**Comment by tvld** [comment]
Just in your readme, in this repo https://github.com/feathersjs-ecosystem/feathers-vuex

**Comment by marshallswain** [comment]
Lol.  I didn't even realized that was there.  It's not actually my demo, but I may replace it at some point in the future.  Check out the feathers-chat-vuex repo for the most up-to-date example of which I'm aware: https://github.com/feathersjs-ecosystem/feathers-chat-vuex

**Comment by tvld** [comment]
thank you ))  The chat app is a big one. For a demo I was looking for minimal viable solution...  So if we can ever get that, ti would be great

**Comment by matiaslopezd** [comment]
@marshallswain The demo is broken.

https://codesandbox.io/s/xk52mqm7o

![image](https://user-images.githubusercontent.com/23618492/83561295-96a3ba80-a4e5-11ea-87cc-5691815dfd43.png)

**Comment by rayfoss** [comment]
> Thank you )) The chat app is a big one. For a demo I was looking for minimal viable solution.
> 
> We still did not decide if feathers is the way to go for us or not. We just finished our [first Nuxt app](https://www.bligson.com) and we are still looking in amazement at the result ))) So a client-server app needs some study for what is the best way to go. We thought Firebase, but dont like Google too much ))

Code sandbox has been changing... for the better definitely. Updated a couple packages and that fixed it.

/close

**Comment by marshallswain** [comment]
Thanks @rayfoss
