### ISSUE TITLE
[Question] What should be the flow for resolving reference ids inside results from server?

### ISSUE THREAD

**Issue by kshitizshankar** [feathersjs-ecosystem/feathers-vuex#446]
Hey,

What would be the right flow of resolving reference ids on the client itself? I know the relationship setup when the data is populated from the API server but for scenarios where that may not be ideal - can it be done in a way where the records can be fetched on setup or something? Basically, how do I remove the dependency of the API returning populated data and yet keep the rest of the app abstracted from that?

Right now, I have something like this in my setup - 
```
  static setupInstance (data, { models, store }) {
    const { Tag} = models.ProductAPI
    if (data.tags) {
      data.tags= data.tags.map(tag => {
        const tagObj = new Tag(tag)
        return tagObj
      })
    } else if (data.tagIds) {
      data.tagIds= data.tagIds.filter(r => r)
      data.tags = data.tagIds.map(tagId => {
        const tagObj = Tag.getFromStore(tagId)
        return tagObj
      })
    }
    return data
  }
}
```

For this to work, I have to make sure that the Tags are pre-loaded before this runs - so I have a pre-loader script that retrieves all the tag objects from the server and adds them to the store. It's been working fine for me so far but it doesn't feel like the right way to go about this. 

The use case seems quite common so not sure if there is already a thread that goes over this or not. 

Thanks!

**Comment by marshallswain** [comment]
I do have a solution for this in mind, but nothing finished.  My current, preferred solution is to populate on the server and use the `useFind` and `useGet` utilities inside of components to retrieve related records.

**Comment by marshallswain** [comment]
My current recommendation is to use `feathers-graph-populate` (https://feathers-graph-populate.netlify.app/) to allow the client to tell the server which relationships to populate with the first request.

I don't have a baked-in solution for doing this after the data has loaded.  For situations that require doing this after the initial request (where using `$populateParams` is not an option) I usually use the `useFind` and `useGet` Composition API utilities to bring in the data that's required.  This keeps the data reactive to when the base record changes, and only requires a few lines of code.

**Comment by kshitizshankar** [comment]
@marshallswain Oh awesome - looks like what I've been trying to find exactly! I'll check it out and see how it would fit into my specific use-case. Thanks!
