### ISSUE TITLE
How to configure responseEntityField

### ISSUE THREAD

**Issue by hiob10hiob** [feathersjs-ecosystem/feathers-vuex#453]
How to configure the auth plugins [state](https://vuex.feathersjs.com/auth-plugin.html#state )?

**Comment by marshallswain** [comment]
Good catch!  This wasn't actually possible.  This is fixed in `feathers-vuex@3.9.1`.  Once you upgrade, you'll be able to pass `entityIdField` and `responseEntityField` as options to the auth plugin.
