### ISSUE TITLE
useGet not reactive on props

### ISSUE THREAD

**Issue by bzd2000** [feathersjs-ecosystem/feathers-vuex#456]
Hi,
It seems that the useGet is not detecting a prop change when the prop contains the id of the model to get

### Steps to reproduce
I have a toolbar with 2 buttons for 2 portfolios (each with its own Id)
when clicking on the button it will chain to the portfolio via the router-view (with props activated)

when clicking on the button of the first portfolio, the page is correctly loaded. (/portfolios/5e81cc1ae49c7b67d5cd1f8f)
then when clicking on the button with the second portfolio, I'm chaining the the second portfolio (/portfolios/5e81cc14e49c7b67d5cd1f8e) but the the data in the page is not refreshed based on the new porfolioId

I see in the vue dev tools that the prop is changing from one portfolioId to the other, but the useGet is not triggered based on the change of the portfolioId.

```
export default {
  name: "Portfolios",
  props: {
    portfolioId: {
      type: String,
      required: true
    }
  },
  setup(props, context) {
    const {item: portfolio, isPending} = useGet({
      model: Portfolio,
      id: props.portfolioId
    });

    return {
      portfolio,
      isPending,
    };
  }
};
```

### Expected behavior
I would expect that the useGet is triggered on the change of props.portfolioId

### Actual behavior
Currently useGet is not triggered on the change of props.portfolioId and so the data of the previous portfolio is still shown

### System configuration
npm: '6.14.4',
node: v13.8.0
quasar: 1.6.0
feathers-vuex: 3.9.0

**Comment by marshallswain** [comment]
I think the merging of options into a new object is probably breaking reactivity for the prop.  I believe the problem is here: https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/src/useGet.ts#L51

It would be nice if this would auto-update for props, so I'll leave this open until one of us gets around to fixing it.

**Comment by marshallswain** [comment]
In the meantime, please use the workaround of wrapping the prop in a computed property, which will guarantee that the `id` makes it through with reactivity:

```js
import { computed } from '@vue/composition-api'

export default {
  name: "Portfolios",
  props: {
    portfolioId: {
      type: String,
      required: true
    }
  },
  setup(props, context) {
    const {item: portfolio, isPending} = useGet({
      model: Portfolio,
      id: computed(() => props.portfolioId)
    });

    return {
      portfolio,
      isPending,
    };
  }
};
```

**Comment by bzd2000** [comment]
Work-around works!

I tried also with a computed property, but did it the wrong way.

thx!

**Comment by marshallswain** [comment]
This isn’t technically a big, since I intended it to be used with a computed property.  I didn’t consider the use case of directly passing a prop, which is funny now that I think of it.  I’m definitely going to look at why it takes to implement this feature.  Thanks for pointing this out.

**Comment by J3m5** [comment]
[This conversation](https://discordapp.com/channels/325477692906536972/568037134968160256/694822646726262845) might be useful

**Comment by bzd2000** [comment]
> [This discord conversation](https://discordapp.com/channels/325477692906536972/568037134968160256/694822646726262845) might be useful

what channel is this?

**Comment by J3m5** [comment]
It is the [vue land server](https://discordapp.com/invite/HBherRA) on the vue3-discussions channel.

**Comment by marshallswain** [comment]
As of `@vue/composition-api@0.6.0` there is a built-in way of making sure props stay reactive:

https://vue-composition-api-rfc.netlify.app/api.html#toref

![Screen Shot 2020-06-08 at 3 04 12 PM](https://user-images.githubusercontent.com/128857/84080376-563ab580-a999-11ea-9081-6353326c734b.jpg)

After playing with this more, wrapping the prop in a ref seems to be the only way to keep this reactive.  This can be achieved using `computed` or `toRef`.
