### ISSUE TITLE
Query new data from the server whenever the store data (local data) changes.

### ISSUE THREAD

**Issue by juancampuzano** [feathersjs-ecosystem/feathers-vuex#461]
I  want to query new data from the server whenever the store data changes. Is it possible for `FeathersVuexFind`?

I am reading the following [link](https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/docs/data-components.md) but only a new query was executed when the `query` changes or the `queryWhen` parameter, however, there is no parameter that is updated when data in Store (local data) changes.

**Comment by marshallswain** [comment]
It's currently only possible with useFind and makeFindMixin, since you'd have to wire up some code manually in your component to do the watching.

**Comment by marshallswain** [comment]
After thinking this through for a while, the best way to handle this would be to use the Vue APIs.  I'm going to show this in the composition API way, even though it still applies in the Vue 2 "options" API.

```vue
<script>
import { models } from 'feathers-vuex'
import { computed, watch } from 'vue'
// import { watch } from '@vue/composition-api'

export default {
  name: 'MyComponent',
  setup(props context) {
    const allTodosInStore = computed(() => {
      return models.api.Todo.findInStore({ query: {} }).data
    })
    watch(
      () => allTodosInStore, 
      allTodos => {
        // Do whatever you're going to do, here.
      },
      // Optionally watch for changes deep in all objects
      { deep: true })
  }
}
</script>
```
