### ISSUE TITLE
Model's idField ignored

### ISSUE THREAD

**Issue by tanc** [feathersjs-ecosystem/feathers-vuex#463]
### Steps to reproduce

This is the first time I'm using feathersjs and vuex so apologies if I've misunderstood the documentation.

I have a bikes service that interacts with my backend service. I'm able to fetch my data fine but I'm struggling to patch it back to the server.

I have the following `idField` specified on my bikes model:
```
...
const servicePath = 'bikes'
const servicePlugin = makeServicePlugin({
  Model: Bike,
  idField: 'bikeId',
  debug: true,
  service: feathersClient.service(servicePath),
  servicePath,
})
...
```
On the server the `bikeId` field is also specified: 

```
export default function (app: Application) {
  const options = {
    Model: createModel(app),
    paginate: app.get('paginate'),
    id: 'bikeId',
  };
  ...
```
After a successful `useFind` the state for bikes shows that the correct idField is set in `$store.state.bikes.idField` but that field isn't used as the id, instead it is using the `_id` field from mongo on the server:
```
{
  "ids": [
    "5e9acedc2909ac001aa7ab85",
    "5e9acedc2909ac001aa7ab87",
    "5e9acedc2909ac001aa7ab88",
    "5e9acedc2909ac001aa7ab89",
    "5e9acedc2909ac001aa7ab86",
    "5e9acedc2909ac001aa7ab8b",
    "5e9acedc2909ac001aa7ab8a",
    "5e9acedc2909ac001aa7ab8c"
  ],
  "keyedById": {
    "5e9acedc2909ac001aa7ab85": {
      "stravaAthleteId": 2164652,
      "bikeId": "b2680865",
      "order": 1,
      "_id": "5e9acedc2909ac001aa7ab85",
      "bikeName": "Canyon Dude",
      "resourceState": 2,
      "totalDistance": 3046948,
      "updatedAt": "2020-04-20T07:41:45.262Z",
      "createdAt": "2020-04-19T17:35:35.849Z"
    }
...
```

When I use the model's `save` method the id used for the patch is the long mongo id which the server ignores as it isn't using that id to match records, it is expecting the `bikeId` field's value instead. If I log the incoming requests on the server in the patch method, I can see the id is not the correct one, for example: `Incoming patch with id:  5e9acedc2909ac001aa7ab8c` 

I'm using the rest client on a Nativescript built Android app (currently just in simulator). Connections between server and client are working fine.

### Expected behavior
I would expect the model's `save` method to use the value of the configured `idField`.

### Actual behavior
Instead the model's `save` method uses the `_id` field as the id which doesn't match what the server is expecting.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions**:
```
feathers-vuex@3.9.1
vuex@3.1.3
feathers@4.5.2
```

**NodeJS version**: `v12.16.1`

**Operating System**: Linux

**Browser Version**: Frontend is using Nativescript/Android

**React Native Version**: N/A. Using Vue and Nativescript

**Module Loader**: Webpack

**Comment by tanc** [comment]
I had a poke around in the code and I think my issue is related to there being a `_id` field in the result sent back from the server. In `getId` the comment says it searches in the following order:
```
Get the id from a record in this order:
  1. id
  2. _id
  3. the `idField`
```
In after hooks on both the server and client I've removed the `_id` field but now when I use the save method on the client it sends `create` instead of `patch`. I will continue investigating.

**Comment by tanc** [comment]
Oh I should mention that after removing the `_id` property, in the client store the fields are now correctly indexed by `bikeId`:

```
{
  "ids": [
    "b2680865",
    "b2910542",
    "b6675209",
    "b4062849",
    "b6114126",
    "b2084322",
    "b4578164",
    "b5113219"
  ],
  "keyedById": {
    "b2680865": {
      "stravaAthleteId": 2164652,
      "bikeId": "b2680865",
      "order": 0,
      "bikeName": "Canyon Dude",
      "resourceState": 2,
      "totalDistance": 3046948,
      "updatedAt": "2020-04-20T07:41:45.262Z",
      "createdAt": "2020-04-19T17:35:35.849Z"
    },
...
```

**Comment by tanc** [comment]
If I define my model with an explicit `idField` it seems to work:

```
class Bike extends BaseModel {
  constructor(data, options) {
    super(data, options)
  }
  static modelName = 'Bike'
  static idField = 'bikeId' // <-- Added explicit idField here
}
```

I tried adding `idField` to the options in the constructor but that seems to get ignored.
If adding a static property is the solution I'm happy with that but I didn't come across it in the docs. Do you think this is correct or did I miss something while reading the docs?

**Comment by J3m5** [comment]
Your issue is related the function [getId](https://github.com/feathersjs-ecosystem/feathers-vuex/blob/51ea4f05cd6b5e449f698d7e9c3c2b9fbcf3e3f2/src/utils.ts#L220).
Like stated in the comment: 

>  Get the id from a record in this order:
> 1. id
>  2. _id
> 3. the `idField`

The solution would be easy, check with the idField first.
But maybe @marshallswain had a good reason to get it in that order.
If it's ok for you Marshal, I'll submit a PR, but if there is people that rely on this behavior, 
this could be a breaking change, no?

**Comment by marshallswain** [comment]
This is a big.  Please file a PR and I’ll do a release.

**Comment by J3m5** [comment]
[PR](https://github.com/feathersjs-ecosystem/feathers-vuex/pull/468) submitted.
You might want to check on this [PR](https://github.com/feathersjs-ecosystem/feathers-vuex/pull/467) too.
