### ISSUE TITLE
Version 3.9.1 crash when instanciating feathersVuex without any options

### ISSUE THREAD

**Issue by sebastien-prudhomme** [feathersjs-ecosystem/feathers-vuex#464]
### Steps to reproduce

Instanciate feathersVuex without any options (version 3.9.1)

### Expected behavior

It works as in version 3.9.0

### Actual behavior

In browser console:

```
Uncaught (in promise) TypeError: Cannot read property 'serverAlias' of undefined
```

This code in ```index.ts```:

```
  if (!options.serverAlias) {
    throw new Error(
      `You must provide a 'serverAlias' in the options to feathersVuex`
    )
  }
```

should be executed after this code:

```
  options = Object.assign({}, defaults, options)
```

Seems this bug was introduces by this commit 154b71820738b6fe8cdd68a462f31cdbff0d083e

**Comment by marshallswain** [comment]
Thanks for the catch.  Fixed in master.  I'll release to npm, soon.
