### ISSUE TITLE
Bug: FeathersVuexFind components

### ISSUE THREAD

**Issue by Barbapapazes** [feathersjs-ecosystem/feathers-vuex#466]
### Steps to reproduce

I copied the code from the example [server-side pagination using FeathersVuexFind components](https://vuex.feathersjs.com/data-components.html#server-side-pagination). But, when I try to change the skip value, nothing append. So I added the watch property: 
```js
watch="query"
```
In the documentation, at [distinct query and fetchQuery](https://vuex.feathersjs.com/data-components.html#use-a-distinct-query-and-fetchquery), we can read:
> the watch strings will be modified internally to watch the fetchQuery object. This means if you are watching query.userId and you add a fetchQuery, the component is smart enough to know you meant fetchQuery.userId

But, it is not exactly what happened !

I found this in the source code:
```ts
const watch = Array.isArray(this.watch) ? this.watch : [this.watch]
 if (this.fetchQuery || this.query) {
   watch.forEach(prop => {
     if (typeof prop !== 'string') {
       throw new Error(`Values in the 'watch' array must be strings.`)
     }
     if (this.fetchQuery) {
       if (prop.startsWith('query')) {
         prop.replace('query', 'fetchQuery')
       }
     }
     this.$watch(prop, this.fetchData)
   })
   this.fetchData()
 }
```

But the replace() method returns a new string ([mdn js doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)). And the return case is not handle !

### Expected behavior
We expected that when we provided a query and a fetchQuery, the watch look at the changes of the fetchQuery, not the query.

### Actual behavior
Actually, the watch will watch the query, even a fetchQuery is provided

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
"feathers-vuex": "^3.9.1"
```

**NodeJS version**:
```
v12.14.1
```

**Operating System**:
```
Windows 10 Pro, version 1909
```

**Browser Version**:
```
Edge (Chromium), Dev channel, Version 84.0.488.1 (Official build) dev (64-bit)
```

**Comment by J3m5** [comment]
Thank you!
Would you mind to submit a pull request to fix this issue?

**Comment by Barbapapazes** [comment]
I'm working on it !

**Comment by marshallswain** [comment]
Closing now that the PR has been merged
