### ISSUE TITLE
`Model.findInStore` needs to be updated to accept `ref` values.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs-ecosystem/feathers-vuex#469]
`Model.findInStore` needs to be updated to accept `ref` values.

**Comment by marshallswain** [comment]
Fixed in https://github.com/feathersjs-ecosystem/feathers-vuex/commit/c8c2f7f4075e95419dfd38cdcbd39dd0ba6ef2cc

**Comment by J3m5** [comment]
Just for information, vue-next implement a [ `unref` utility function](https://github.com/vuejs/vue-next/blob/a0e2c1287466567d945e87496ce2f922f3dc6d8c/packages/reactivity/src/ref.ts#L84).

**Comment by marshallswain** [comment]
That should be part of the Vue Composition API’s exports.

**Comment by J3m5** [comment]
There is [isRef](https://github.com/vuejs/composition-api/blob/d1715e4985401fe62714cbea051219269454b5d6/src/reactivity/ref.ts#L139) 
so we can re-implement it or propose it to composition-api repo.

**Comment by J3m5** [comment]
Well, it [has been done](https://github.com/vuejs/composition-api/pull/309) but I don't see how it ended up.

**Comment by marshallswain** [comment]
We should totally implement it ourselves, the same as that link.  I’ve opened https://github.com/feathersjs-ecosystem/feathers-vuex/issues/471 <https://github.com/feathersjs-ecosystem/feathers-vuex/issues/471> as a reminder.
