### ISSUE TITLE
Auth tests not running

### ISSUE THREAD

**Issue by hamiltoes** [feathersjs-ecosystem/feathers-vuex#475]
### Steps to reproduce

1. Clone repo
2a. Run tests scripts
2b. Debug tests

### Expected behavior

all tests run

### Actual behavior

`./test/auth.test.js` and `./test/auth-module/actions.test.js` do not run

### System configuration

Both `package.json`'s `test` script and the VSCode debug config are setup to only run TS files.

I could be mistaken but both files look a little dated (written for an older version) and could probably use a good update.

**Comment by marshallswain** [comment]
Thanks for filing this issue.  We should definitely bring them up to date.  I'd forgotten all about it.

**Comment by marshallswain** [comment]
I'm not sure when this changed, but the tests are for sure running with `yarn test`, now.
