### ISSUE TITLE
WS: Service state ids do not include new model ids added on the client

### ISSUE THREAD

**Issue by nakedgun** [feathersjs-ecosystem/feathers-vuex#489]
### Steps to reproduce

1. Setup feathers client + a service plugin based upon the docs: e.g. [here](https://vuex.feathersjs.com/getting-started.html#feathers-client-feathers-vuex) or [here](https://vuex.feathersjs.com/nuxt.html#working-with-auth-nuxt). 

2. Set feathers client to web sockets

3. Create a new model instance and save it:

```
const { Todo } = this.$FeathersVuex.api;
const todo = new Todo({
    text: 'Something'
});
await todo.save(); 
console.log(todo.id) // 1
```

### Expected behavior
`console.log(this.$store.state.todo.ids) // should be [1] `

### Actual behavior
`console.log(this.$store.state.todo.ids) // is actually [0]`

With **todos.ids** being out of sync with **todos.keyedById**, you get weirdness. For example, if sometime later you perform todo.find(), it will silently fail to update todo 1.

If you set the feathers client to use rest instead, it behaves as expected.

### System configuration

"feathers-client": "^2.4.0",
"feathers-hooks-common": "^4.20.7",
"feathers-vuex": "^3.9.1",

**Comment by hamiltoes** [comment]
I have a hunch I broke this.

Take a look at the `updateTemp` mutation. It is moving the temp from `tempsById` to `keyedById` but it also needs to put the new id in `ids`.

**Comment by nakedgun** [comment]
@hamiltoes good hunch. Adding this line seems to fix it:

```
// If an item already exists in the store from the `created` event firing
// it will be replaced here
Vue.set(state.keyedById, id, temp)
if (!state.ids.includes(id)) {
  state.ids.push(id)
}
```

**Comment by marshallswain** [comment]
I'm pretty sure this can be closed, now.  Please reopen if I'm mistaken.
