### ISSUE TITLE
Feathers Error When Sending Patch Request

### ISSUE THREAD

**Issue by coderinblack08** [feathersjs-ecosystem/feathers-vuex#493]
After trying to copy a patch request form the docs and running it, I keep getting a feathers error saying that BAD REQUEST 400: "Cast to ObjectId failed for value "{ name: 'Hi', completed: true }" at path "_id" for model "schools"". Can anyone help me?

Feathers vuex version: 3.10.4
code: 
``` js
let data = { name: 'Hi', completed: true };
this.$store.dispatch('schools/update', [1, data, {}]);
```

**Comment by J3m5** [comment]
This error come from feathers. Are you using Mongoose ?
The error might happens because the number can"t be converted to a valid ObjectId.

**Comment by coderinblack08** [comment]
Yeah I am using mongoose, can you please clarify what you mean by "the number can"t be converted to a valid ObjectId."

**Comment by coderinblack08** [comment]
This error even appears when I send a get request.
``` js
this.$store.dispatch('schools/get', { query: {} });
```

**Comment by coderinblack08** [comment]
Also, I have checked the docs, they have a way of updating/patching, but how can I make it so id does it to an existing model?
``` js
import { models } from 'feathers-vuex'
const { Todo } = models.api

const todo = new Todo({ description: 'Do Something', isComplete: false })

todo.patch({ data: { isComplete: true } })
```

**Comment by J3m5** [comment]
Mongoose will try to convert the id you pass to the type it should be, and the ids in mongodb are [ObjectIds](https://docs.mongodb.com/manual/reference/bson-types/#objectid).
And the number 1, in your case can't be converted to an ObjectId.
So to make it works, the update action must be called with an id that is a valid ObjectId ans that exist in you mongodb collection.
And the same goes for the get method, unless you correctly pass the params: `[id, params]`.

**Comment by J3m5** [comment]
Each items in the store has those methods on it, so the update/patch will work on it.

**Comment by coderinblack08** [comment]
🙏🙏🙏🙏🙏 Thanks so much, Better read the documentation properly next time 😉
