### ISSUE TITLE
'auth/user' is not reactive in different tabs

### ISSUE THREAD

**Issue by yohane55** [feathersjs-ecosystem/feathers-vuex#494]
I am using `user` getter on Nuxt SPA. But when I logout on one tab the other tab stays logged in and can perform any action. How can we manage to have a global state in all tabs?

here is how I get the user object
``` 
computed : {
 user() {
      return this.$store.getters["auth/user"];
    },
}

```

**Comment by yohane55** [comment]
I end up using other modules to share mutation on auth plugin so other tabs update to latest state.

**Comment by ericuldall** [comment]
Hey I think this is an issue for me. I do the following...
```
export default {
  computed: {
    user () {
      return this.$store.getters["auth/user"];
    }
  }
}
```

This let's me access the auth user in a simple way. However, this value does not seem to be reactive. If I was to do the following:

```
this.user.email = 'newemail@test.com';
this.user.save();
```

The save will work, but my user object won't be updated until I change routes or reload the page. Is this the intended behavior?

**Comment by cs-matt** [comment]
Why was this closed? It's not reactive for me in Nuxt either.
