### ISSUE TITLE
useFind is getting spammed - normal?

### ISSUE THREAD

**Issue by BaroDevelopment** [feathersjs-ecosystem/feathers-vuex#495]
### Steps to reproduce
Consider the following computed value allTodos:
```js
            allTodos(){
                const {Todo} = this.$FeathersVuex.api
                const params = () => {
                    return{
                        query: {
                            // $sort: { createdAt: 1 },
                            // $limit: 25
                        }
                    }
                }
                const todos  = useFind({
                    model: Todo,
                    params
                })
                console.log(todos.items)
                return todos.items
            }
        },
```

the todos.items is getting logged into the console every second. Is this intended? 

### Expected behavior
Shouldn't it be event based?

### Actual behavior
the todos.items is getting logged into the console every second. Is this intended?

**Comment by hamiltoes** [comment]
`useFind` is a Vue composition function and should only be used in a component's `setup` method.

If you want to call find in a computed, use the `find` action in the Vuex store. Since you already accessed the model, just call the model's static method `model.find` or `model.findInStore`

**Comment by BaroDevelopment** [comment]
Thanks for the answer. That makes actually sense.
What is the difference between useFind and find()?

**Comment by marshallswain** [comment]
@BaroDevelopment `useFind` is the composition-api equivalent to the `makeFindMixin`.  If you're not using the `@vue/composition-api` plugin, then you need to use `makeFindMixin` to get the same functionality.

`makeFindMixin` and `useFind` both use the `find` action and the `find` getter to perform realtime queries with fall-through cache.  They give you a declarative api for working with reactive query data, meaning when you change anything in the query, the lists automatically update to match the queries.  It's really performant and is a highly maintainable way of adding functionality to apps.

**Comment by marshallswain** [comment]
And to confirm, yes, `useFind` must be used in a component's `setup` method.
