### ISSUE TITLE
https://vuex.feathersjs.com/ is down - This Domain Name Has Expired

### ISSUE THREAD

**Issue by virus-pk** [feathersjs-ecosystem/feathers-vuex#497]
### Steps to reproduce

- [ ] Hit URL
- [ ] [vuex.feathersjs.com](https://vuex.feathersjs.com/)

**Browser Version**:

Google Chrome
Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by virus-pk** [comment]
is there another way to see the docs?

**Comment by J3m5** [comment]
It is not only about feathers-vuex, the whole domain has expired.

[https://feathersjs.com/](https://feathersjs.com/)

**Comment by fratzinger** [comment]
up and running again. I think this can be closed :)
