### ISSUE TITLE
[Question] How to access the user id

### ISSUE THREAD

**Issue by BaroDevelopment** [feathersjs-ecosystem/feathers-vuex#499]
Hello,
the user_id is not set when i refresh the website because store is not ready yet.
Any idea how to fetch the user_id once store is filled?

I searched in the docs but couldn't find anything that can help me with this problem.

```js
        async created() {

            await this.$store.dispatch('')

            const {Todo, User} = this.$FeathersVuex.api
            const user_id = this.$store.state.auth.user.id

            const {data} = await Todo.find({
                query: {
                    user_id,
                    $limit: 40
                }
            })
        }
```

Thanks in advance!

**Comment by J3m5** [comment]
You must call the authenticate action before your app startup in order to authenticate with the JWT stored in localstorage.
Then the user will be available.
