### ISSUE TITLE
Compilation (or Loading) problem for ES6+

### ISSUE THREAD

**Issue by lturel** [feathersjs-ecosystem/feathers-vuex#507]
Hi Marshall,

I am developing a small app  with  **QuasarJS** (1.9.9) + **Feathers** (4.5.5) + **Feathers-Vuex** (3.11.5).
**Node** (12.9.1).

In quasar.conf.js  there exists,   transpileDependencies: ["feathers-vuex"].   
I am working on  Win 10.

On the client side;  if I compile by  >  **quasar dev,**   in compile messages it says,  **Generating legacy js code (ES5); use "--modern" param for ES6+**,   and  it completes normally,  eveything works as expected.

But if I compile by  >  **quasar dev –modern**  (which Quasar says necessary for ES6+)  
it gives the following warning in terminal  and I can not get info from users service  (no login form).

        WARNING  Compiled with 1 warnings                                                                              12:51:23
        warning  in ./src/store/services/users.js

        Module parse failed: Unexpected token (12:19)
        File was processed with these loaders:
         * ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js
         * ./node_modules/eslint-loader/dist/cjs.js
        You may need an additional loader to handle the result of these loaders.
        |   }
        |   // Required for $FeathersVuex plugin to work after production transpile.

        >   static modelName = "User";

        |   // Define default properties here
        |   static instanceDefaults() {

        @ ./src/store/services sync nonrecursive .js$
        @ ./src/store/index.js
        @ ./.quasar/app.js
        @ ./.quasar/client-entry.js
        @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

The console on the browser looks like; 

![image](https://user-images.githubusercontent.com/44019582/87873309-31d6ed80-c9c9-11ea-9ff0-2761e6591fef.png)

On a related topic,      QuasarJS says  (https://quasar.dev/quasar-cli/app-upgrade-guide#What%E2%80%99s-new-in-v2)
         `The JS transpilation (with the help of Babel) has been rethought from the ground up (now using 
         core-js v3). It will now transpile based on the Browser compatibility that you configure. It will no 
         longer go transpiling directly to ES5, but it will look for exactly what JS features need transpiling 
         based on the configured browsers. Be mindful about it though, as it is sufficient to add one “bad 
         apple” in the options list and that will dumb down your code back to ES5.`

Although I can continue with ES5 compilation for now,  for near future works,   ES6 will be usual way.
What is the problem at this point    and    what could be the solution for this issue?
Thanks in advance,

Levent Turel

**Comment by J3m5** [comment]
Class static fields are not handled by webpack as it's still a stage 2 ECMA feature.
The equivalent of this is to assign the value on the class once it has been created.

[See here in the docs](https://vuex.feathersjs.com/model-classes.html#extending-the-basemodel-class)

I have the same stack as you and this is what I do.

**Comment by lturel** [comment]
@J3m5 thanks a lot.
It worked for me too.

Replaced the static definitions  in ./src/store/services/users.js    by;

```
    class User extends BaseModel {}

    ```
    User.modelName = 'User'
    User.instanceDefaults = function() {
      return {
          email: '',
          password: ''
      }
    }
```
```
