### ISSUE TITLE
mapGetters Find params query with nested object

### ISSUE THREAD

**Issue by apmcodes** [feathersjs-ecosystem/feathers-vuex#508]
Server is returning nested/ relationship object as below. But, its not visible in the UI. How can we query it from store.

FindTickets (mapGetters) returning tickets with nested associated users
```
id: 23,
user: {
email: (...)
id: (...)
property: "vto"
}
``` 
Trying to filter tickets by users belonging to property in the UI. Correct results are returned by Feathers but not able to filter it in the UI.

params.query 
```
$limit: 10
$skip: 0
$sort: {createdAt: -1}
user: {
   property: "vto"
}
```

**Comment by J3m5** [comment]
FeathersVuex use the sift/mongo syntax for querying so you can use the dot syntax like that:
```js
{
  query: {
    $limit: 10,
    $skip: 0,
    $sort: { createdAt: -1 },
    "user.some.prop": "value",
  }
}
```

**Comment by apmcodes** [comment]
Thank you @J3m5. This helped filter data.
