### ISSUE TITLE
On instance.save related object from store is not populated

### ISSUE THREAD

**Issue by apmcodes** [feathersjs-ecosystem/feathers-vuex#509]
### Steps to reproduce

Create a new item using instance.save which has a userId.
```
id: 23,
userId: 5
```

Need to populate the related user from the store
```
id: 23,
userId: 5
user: {
  email: (...)
  id: (...)
}

```

Model is using setupInstance
```
    static setupInstance(data, { models }) {
        if (data.user) {
            data.user = new models.api.User(data.user);
        }
        return data
    }
```

Should we manually populate related object from store may be using hook or something else? Have gone through the docs but not able to understand how to achieve this.

### System configuration
```
"@feathersjs/feathers": "^4.5.5",
"feathers-vuex": "^3.11.5",

```

**Comment by J3m5** [comment]
You are checking `data.user` and not `data.userId`.

**Comment by apmcodes** [comment]
@J3m5 That made it work. Thank you very much. 

```
    static setupInstance(data, { models }) {
        if (data.user) {
           // Gets triggered on find
            console.log('has User')
            data.user = new models.api.User(data.user);
        } else if (data.userId && !data.user) {
            // Gets triggered on create as well as patch
            console.log('no User');
            data.user = models.api.User.getFromStore(data.userId);
        }
        return data;
    }
```

Btw, observed the following
1) setupInstance is being called twice on every create/ patch (attached screenshot)

![Screenshot from 2020-07-22 21-52-27](https://user-images.githubusercontent.com/13360356/88201870-acbc3480-cc65-11ea-87a9-6e4497e10ac5.png)
