### ISSUE TITLE
[Question] How to listen on custom events from a feathersjs server.

### ISSUE THREAD

**Issue by DaniGTA** [feathersjs-ecosystem/feathers-vuex#512]
**I have a Service in feathersjs that sends custom events and i recieve them via the websocket, but i dont know how i can handle these events in feathers-vuex ?**

The custom event is binded to a service so the websocket event name looks like this: 

`["service/a customevent", {data:""}]`
  --^^^^^^^^^^^^^^^
  --Websocket event name

**Comment by marshallswain** [comment]
You would do this the same way that feathers-vuex does this internally for the standard FeathersJS events.  Here's the place it is done internally: https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/src/service-module/make-service-plugin.ts#L139
