### ISSUE TITLE
Question: How can I create a Model-less Service?

### ISSUE THREAD

**Issue by tasker204** [feathersjs-ecosystem/feathers-vuex#517]
I have a service on the server that is not connected to my DB, it is simply used to send emails using the create method. 
How can I create a service for this on my frontend?

**Comment by marshallswain** [comment]
The short answer is that you don't create a service without a model class.

There is an open issue for automatically creating a model class, which is certainly interesting, but I've been putting my time more into features that really make a big difference in the amount of boilerplates code one would typically need to write to accomplish more common tasks.  So this issue has naturally taken a back seat, since I feel like adding a couple lines of code per Service is acceptable.

**Comment by tasker204** [comment]
OK, fair enough. 
Do you have any insight as to how I would go about creating a frontend service for my given scenario? 
Adding a few lines of code is 100% acceptable and something I am very prepared to do. My issue is I'm not very confident that I know where to start. 
What do I use for a model, how to I limit the service to only calls to the create method? Any help at all would be great.

**Comment by marshallswain** [comment]
You would basically create it the same was as any service.  If I were in the same situation, I would just ignore the other methods and annotate the service as being limited to only one of the REST methods.  If you want to go a step further, you can setup a before hook on the client side that returns an `errors.NotImplemented()` from `@feathersjs/errors`.  If it's just to send emails you don't *really* need any `instanceDefaults` or `setupInstance` implementation.  After you follow the instructions for setting up any service (in the docs) you'll be able to do this kind of thing:

```js
import { models } from 'feathers-vuex

const data = {
  to: '',
  subject: '',
  etc: '...'
}
new models.api.Email(data).save()
```

Or you could directly import the feathersClient and use the service:

```js
import { feathersClient } from './feathers-client.js'

feathersClient.service('emails').create(data)
```

**Comment by marshallswain** [comment]
I guess that may be what you're looking for, possibly.  You don't need to use the feathers-vuex wrapper if you don't need Vuex for the service.  If I would have gotten more sleep in the last few days, I'd have caught that earlier.  haha.

**Comment by tasker204** [comment]
Thats great.
I also feel that if I had gotten more sleep I would have been able to figure that out on my own.
I appreciate the time. Thanks!
