### ISSUE TITLE
Documentation Update: Usage of FeathersVuexFormWrapper and diffOnPatch only with eager option

### ISSUE THREAD

**Issue by jniclas** [feathersjs-ecosystem/feathers-vuex#520]
I use a Model with the FeathersVuexFormWrapper. For patches I also use the Model method diffOnPatch.
diffOnPatch takes the new data and fetches old data from the store to get the difference. 
But if the FeathersVuexFormWrapper attribute "eager" is set to true, the clone is first commited and afterwards saved. So the store is updated, before the diffOnPatch is executed and the method can't figure out a difference. 
It is solved by setting the attribute "eager" to false. Could you update the documentation?

(sorry for not using the template)

Best regards and thank you for creating this wonderful tool,
Niclas

**Comment by marshallswain** [comment]
I've updated the docs.  Thank you!
