### ISSUE TITLE
Question: how to implement getOrDefault logic

### ISSUE THREAD

**Issue by shabanovd** [feathersjs-ecosystem/feathers-vuex#525]
### Expected behavior
I need to edit related record to object that provided and can't figure out how to do it with existing methods.
Here an example of steps:
- collect parameters for record
- fetch record from database (if it's not exist yet create new object and set parameters)
- modify object and save it to database

My guess, it should be very close to `FeathersVuexGet` just missing part is `default` argument to provide a way to create object if record do not exist.

Or maybe, I miss something?

**Comment by marshallswain** [comment]
Could you use server side hooks to create the default object on the server?

**Comment by shabanovd** [comment]
@marshallswain no, because I need it for UI 1st and only when user decide to save it should be stored on server. Other words, I would like to have same logic to create new item or edit existing one.

**Comment by shabanovd** [comment]
@marshallswain btw, I have implemented it locally by adding additional function-parameter. `onEmpty` for `find` and `onNothing` for get. I can create PR if you're interesting.

**Comment by marshallswain** [comment]
> no, because I need it for UI 1st and only when user decide to save it should be stored on server. Other words, I would like to have same logic to create new item or edit existing one.

Let me specify details of how this would work.  

1. Perform the `.get` request from the client.
2. Create an after-get error hook on the server.  If the error says that the item doesn't exist, create the default object (do not persist it to the database) and return that as `context.result`.
3. The client receives a default object that has not been persisted to the database.

You can even do the same thing using client-side hooks, if you want to keep it all on the client.  You could even perform the same logic without hooks if you used a promise and in the `catch` block of the `.get` request you create the default object.

**Comment by marshallswain** [comment]
Technically you could even override the BaseModel instance and do this at the Model class layer, if you'd like every `get` request to have this behavior.
