### ISSUE TITLE
FeathersVuexFormWrapper and catching errors

### ISSUE THREAD

**Issue by monks1975** [feathersjs-ecosystem/feathers-vuex#535]
Is there a way that I can catch errors at the component level with FeathersVuexFormWrapper- to notify the user e.g through a toast that the save was unsuccessful. An example would be server side validation; a joi schema error on the server? I have seen examples where a then() is chained to the save method after success, but have found that chaining a catch in the template doesn't work for me.

**Comment by marshallswain** [comment]
If you look at the `save` method in the code, you'll see that the promise is being returned, here: https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/src/FeathersVuexFormWrapper.ts#L65

You can tack a `.catch` onto that in your code and pass it an error handler from your component's scope.

**Comment by monks1975** [comment]
I have been able to catch errors using this pattern:

```
@save="
              () => {
                save().catch(err => handleError(err));
              }
            "
```

If I put a then() in between save and catch however it will go to the then() even on errors.

**Comment by marshallswain** [comment]
Thanks for reporting back, @monks1975!
