### ISSUE TITLE
FeathersVuexCount not found in feathers-vuex

### ISSUE THREAD

**Issue by fasterv410** [feathersjs-ecosystem/feathers-vuex#541]
I can't import FeathersVuexCount component in the feathers-vuex

feathers-vuex: 3.13.0

![Screen Shot 2563-10-19 at 14 14 00](https://user-images.githubusercontent.com/19948344/96413106-584d3480-1215-11eb-9298-37f7a9df1d73.png)

**Comment by marshallswain** [comment]
Looks like it just needs to be imported in `index.ts` and made available in the exports in the same way as is done here: https://github.com/feathersjs-ecosystem/feathers-vuex/blob/master/src/index.ts#L7

Thank you for catching this!
