### ISSUE TITLE
id conversion before passing it into keyedById

### ISSUE THREAD

**Issue by GaborTorma** [feathersjs-ecosystem/feathers-vuex#543]
### Steps to reproduce

When use use object for id (like ObjectId), keyedById didn't found the key, because the id is string in store.

### Expected behavior
Convert the id to String before passing it into keyedById[id].
For examples in utils.js getItemsFromQueryInfo and createRelatedInstance

The solution: keyedById[String(id)]

**Comment by marshallswain** [comment]
This is fixed in the `master` branch, currently.  I'll do a release as soon as we get https://github.com/feathersjs-ecosystem/feathers-vuex/pull/536 merged.  This is a nice addition.  Thanks for opening the issue!
