### ISSUE TITLE
Feathers v4 Socket rollback

### ISSUE THREAD

**Issue by corepay** [feathersjs-ecosystem/feathers-vuex#569]
@marshallswain you're probably aware of https://github.com/feathersjs/feathers/issues/2128.

This affects fresh builds - the app will not launch 

![image](https://user-images.githubusercontent.com/48992923/104065734-a8b1ae00-51d6-11eb-9eff-334bfe9ff029.png)

**Comment by corepay** [comment]
PS I am having problems with client getting events from server - - - Network shows nothing -  is this related ya think?

**Comment by marshallswain** [comment]
Lack of events is likely just a server config issue, if you're in the supported version of socketio

**Comment by J3m5** [comment]
Make sure you use the 2.4.1 version.

**Comment by corepay** [comment]
Ah - after kicking my stuffed Mr. Peabody several times and shouting "why, why, why me?" at the clouds I discovered again how inadequate I am as an engineer after discovering that I need to have a logged in client or register the event in anonymous channel.

I'll go ahead and close issue hoping there are enough keywords here for dummies like me running into similar problems
