### ISSUE TITLE
Remove lodash.values

### ISSUE THREAD

**Issue by marshallswain** [feathersjs-ecosystem/feathers-vuex#587]
![Screen Shot 2021-03-16 at 10 30 28 AM](https://user-images.githubusercontent.com/128857/111345213-ac343c00-8642-11eb-82ca-71f6c846c569.jpg)

**Comment by J3m5** [comment]
I've started working on it and ended-up making a refactor of the getters module.
In fact, this is the only place were there was still the lodash `values` method.

**Comment by marshallswain** [comment]
Awesome.  Could you make these same changes in the vue-demi branch?  I really need to get the documentation done.  That's all that's left to publish.  I was going to switch it to Nuxt, but instead am now choosing to keep what we have.  Time to keep things simple with so much else going on.  

Anyway, thanks for starting the PR.

**Comment by J3m5** [comment]
No problem, do you see anything else that need to be addressed ?

**Comment by fratzinger** [comment]
This is merged in master (#588) and in vue-demi (#593). It's only used in tests on both branches.
To get things cleaned up a little bit, I think this can be closed. Please reopen, if I'm wrong.
