### ISSUE TITLE
add one time sponsor

### ISSUE THREAD

**Issue by dkebler** [feathersjs-ecosystem/feathers-vuex#604]
Can you add one time sponsor like sindre -shorus https://github.com/sponsors/sindresorhus?frequency=one-time
I want to donate but just one time.  I suggest 10,50,100
Thx

**Comment by dkebler** [comment]
or just post a link to send you $$ via paypal

**Comment by marshallswain** [comment]
@dkebler Thanks for pointing this out.  I've created an option for one-time contributions.  I just created one for $25 and set it to allow customizing the amount to whatever you'd like.   I really appreciate this.  Thank you.
