### ISSUE TITLE
$like operator not working in local getters(using sequelize)

### ISSUE THREAD

**Issue by CodeMetric** [feathersjs-ecosystem/feathers-vuex#606]
$like operator is whitelisted in both server and in client via service plugin feathersVuex

**/store/index.js**
```
userPlugin = makeServicePlugin({
    Model: User,
    enableEvents: true, 
	idField: 'id',
    whitelist: ['$like'],
})
```
**/user.vue**
```
...mapGetters("user", {
      findItemInStore: "find",
    }),
...	
const findData = findItemInStore({
        query: {
          name: { $like: "%s%" },
        },
      });
```
The above query throws the error [Vue warn]: Error in render: "Error: Unknown operation $like"

The server returns filtered response correctly but unable to filter the Vuex store using $like operator
	  
### Module versions:
**vue**: 2.6.12,
**Feathers-vuex**: 3.2.1
**NodeJS version**: v12.18.3

**Comment by J3m5** [comment]
The `$like` operator is not available in [sift](https://github.com/crcn/sift.js), the library used to query the vuex stores.

The equivalent would be the [$regex](https://github.com/crcn/sift.js#regex) operator, you can use two different queries, one for the server with `$like`,
and another for the local query, with the `$regex` operator.

**Comment by CodeMetric** [comment]
@J3m5 Thanks for providing me the right direction!
I've used the queries in two different ways as `$like` for server and` $regex `for local getters, and whitelisted `$regex` in store index. Now its working correctly.
